/**
 * Drag & drop of the Builder as pure functions: where the insert indicator goes and which operation a drop becomes.
 * The UI (dnd-kit pointer + keyboard sensors, plus a click-to-add fallback) only measures and calls these; the result is always
 * SchemaOperation[] for the single write funnel (applyOps → PATCH /schema). Rules that hold for EVERY path (pointer, keyboard, click):
 *   - a SLOT is a position between sections (0..n); the indicator and the operation use the same number;
 *   - a trailing Footer stays last: nothing else is inserted after it, and a dragged Footer goes to the end;
 *   - dropping a section on its own slot is a no-op (no operation, so no new version).
 */
import type { SchemaOperation, Section } from "@xweb/types";

export type SectionRect = { id: string; top: number; height: number };

/** slot (0..n) under a vertical position, by the midpoint rule: above a section's middle = before it */
export function slotFromPoint(rects: SectionRect[], y: number): number {
  const sorted = rects.slice().sort((a, b) => a.top - b.top);
  let slot = 0;
  for (const r of sorted) { if (y > r.top + r.height / 2) slot += 1; else break; }
  return slot;
}

const hasTrailingFooter = (sections: Section[]) => sections.length > 0 && sections[sections.length - 1].type === "Footer";

/** highest slot a section of this type may take in this list: before a trailing Footer, otherwise the end */
export function maxSlot(sections: Section[], type: string): number {
  return type !== "Footer" && hasTrailingFooter(sections) ? sections.length - 1 : sections.length;
}
export const clampSlot = (sections: Section[], slot: number, type: string): number => Math.max(0, Math.min(maxSlot(sections, type), slot));

export type AddPlan = { slot: number; ops: SchemaOperation[]; summary: string };

/** Insert a NEW section of a registry component at `slot`. `props` = defaultProps(component); `id` is generated by the caller. */
export function planAdd(sections: Section[], componentType: string, label: string, slot: number, args: { id: string; props: Record<string, unknown>; pageId?: string }): AddPlan {
  const at = clampSlot(sections, slot, componentType);
  const onPage = args.pageId && args.pageId !== "home" ? { pageId: args.pageId } : {};
  return { slot: at, summary: `Thêm ${label}`, ops: [{ type: "ADD_SECTION", ...onPage, sectionType: componentType, sectionId: args.id, props: args.props, index: at }] };
}

export type MovePlan = { kind: "move"; from: number; to: number; ops: SchemaOperation[] } | { kind: "noop"; reason: string };

/**
 * Move an existing section to `slot` (a slot of the ORIGINAL list, as the indicator showed it). The engine's MOVE_SECTION `index` is the
 * index AFTER the section is taken out (arrayMove), so a slot below the old position shifts down by one.
 */
export function planMove(sections: Section[], sectionId: string, slot: number): MovePlan {
  const from = sections.findIndex((s) => s.id === sectionId);
  if (from < 0) return { kind: "noop", reason: "Không tìm thấy mục đang kéo." };
  const type = sections[from].type;
  const rest = sections.filter((s) => s.id !== sectionId);
  const inRest = slot > from ? slot - 1 : slot;
  const to = type === "Footer" ? rest.length : Math.max(0, Math.min(maxSlot(rest, type), inRest));
  if (to === from) return { kind: "noop", reason: "Mục đã ở đúng vị trí." };
  return { kind: "move", from, to, ops: [{ type: "MOVE_SECTION", sectionId, index: to }] };
}

/** keyboard: move one position up (-1) or down (+1) */
export function planStep(sections: Section[], sectionId: string, delta: -1 | 1): MovePlan {
  const from = sections.findIndex((s) => s.id === sectionId);
  if (from < 0) return { kind: "noop", reason: "Không tìm thấy mục." };
  return planMove(sections, sectionId, delta < 0 ? from - 1 : from + 2);
}

/** click-to-add (the no-drag fallback): after the selected section, otherwise at the end (before a trailing Footer) */
export function slotForClickAdd(sections: Section[], selectedId: string | null, type: string): number {
  const i = selectedId ? sections.findIndex((s) => s.id === selectedId) : -1;
  return clampSlot(sections, i >= 0 ? i + 1 : sections.length, type);
}

/** the id of the section the indicator sits before (for the label "Thả vào trước …"), or null at the end */
export function slotNeighbours(sections: Section[], slot: number): { before: Section | null; after: Section | null } {
  return { before: sections[slot - 1] ?? null, after: sections[slot] ?? null };
}

/**
 * A slot counted over the RENDERED rectangles (what the pointer sees) back to an index in the section list. Sections the preview has no
 * renderer for have no rectangle, so the two lists can differ.
 */
export function sectionIndexForSlot(sections: Section[], rects: SectionRect[], slot: number): number {
  const sorted = rects.slice().sort((a, b) => a.top - b.top);
  if (!sorted.length) return sections.length;
  if (slot < sorted.length) { const i = sections.findIndex((s) => s.id === sorted[slot].id); return i < 0 ? sections.length : i; }
  const last = sections.findIndex((s) => s.id === sorted[sorted.length - 1].id);
  return last < 0 ? sections.length : last + 1;
}

/** y (px, inside the preview) where the insertion line is drawn for a rendered-rectangle slot */
export function indicatorY(rects: SectionRect[], slot: number): number {
  const sorted = rects.slice().sort((a, b) => a.top - b.top);
  if (!sorted.length) return 16;
  if (slot < sorted.length) return Math.max(0, sorted[slot].top);
  const last = sorted[sorted.length - 1];
  return last.top + last.height;
}
