/**
 * Page tree of a multi-page Page Schema: pure functions, no React, no API.
 * Mirrors what the backend (PageSchemaValidator / SchemaPatchEngine) accepts so the UI never offers an operation the server will refuse:
 * slug `^[a-z0-9]+(-[a-z0-9]+)*$` ≤ 60 chars, reserved slugs, ≤ 20 pages, ≤ 12 navigation links, the root `sections` array is the home page.
 * Every function that changes the site RETURNS typed SchemaOperation[] for the single write funnel (applyOps → PATCH /schema); none mutates its input.
 */
import type { NavLink, PageSchema, SchemaOperation, Section, SitePage } from "@xweb/types";
import { notReady, type Readiness } from "./readiness";

export const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
export const RESERVED_SLUGS: ReadonlySet<string> = new Set(["assets", "api", "sites", "_app", "_preview", "_access", "_forms", "__factory", "404", "index", "home", "static"]);
export const MAX_PAGES = 20;
export const MAX_NAV = 12;
export const HOME_ID = "home";

export type PageNode = {
  id: string; title: string; slug: string;
  /** public route: "/" for home, "/gioi-thieu/" for a page */
  route: string; home: boolean; sectionCount: number;
  /** position in the navigation menu, null when the page has no menu link */
  navIndex: number | null;
};

export const slugify = (s: string): string => s.normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/đ/g, "d").replace(/Đ/g, "d").toLowerCase()
  .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);

export const routeOf = (slug: string): string => (slug ? `/${slug}/` : "/");

export function listPages(schema: PageSchema): PageNode[] {
  const nav = schema.site?.navigation ?? [];
  const navIndexOf = (id: string) => { const i = nav.findIndex((l) => l.pageId === id); return i < 0 ? null : i; };
  const home: PageNode = { id: HOME_ID, title: schema.site?.home?.title || "Trang chủ", slug: "", route: "/", home: true, sectionCount: schema.sections.length, navIndex: navIndexOf(HOME_ID) };
  return [home, ...(schema.pages ?? []).map((p): PageNode => ({ id: p.id, title: p.title, slug: p.slug, route: routeOf(p.slug), home: false, sectionCount: p.sections.length, navIndex: navIndexOf(p.id) }))];
}

export function sectionsOf(schema: PageSchema, pageId: string): Section[] {
  return pageId === HOME_ID ? schema.sections : schema.pages?.find((p) => p.id === pageId)?.sections ?? [];
}

export type SlugCheck = { ok: true } | { ok: false; reason: string };
export function checkSlug(schema: PageSchema, slug: string, exceptPageId?: string): SlugCheck {
  if (!slug) return { ok: false, reason: "Đường dẫn không được để trống." };
  if (slug.length > 60 || !SLUG_RE.test(slug)) return { ok: false, reason: "Đường dẫn chỉ gồm chữ thường, số và dấu gạch ngang (tối đa 60 ký tự)." };
  if (RESERVED_SLUGS.has(slug)) return { ok: false, reason: `“${slug}” là đường dẫn dành riêng của hệ thống.` };
  if ((schema.pages ?? []).some((p) => p.slug === slug && p.id !== exceptPageId)) return { ok: false, reason: "Đã có trang khác dùng đường dẫn này." };
  return { ok: true };
}

export function uniqueSlug(schema: PageSchema, title: string): string {
  const base = slugify(title) || "trang";
  const taken = (s: string) => RESERVED_SLUGS.has(s) || (schema.pages ?? []).some((p) => p.slug === s);
  let s = base, n = 2;
  while (taken(s)) s = `${base}-${n++}`.slice(0, 60);
  return s;
}

/** the id is generated by the caller (UI uses random, tests pass a fixed one) */
export function opsAddPage(schema: PageSchema, title: string, id: string): { ops: SchemaOperation[]; summary: string } | { error: string } {
  const t = title.trim();
  if (!t) return { error: "Hãy nhập tên trang." };
  if ((schema.pages ?? []).length >= MAX_PAGES) return { error: `Tối đa ${MAX_PAGES} trang.` };
  return { ops: [{ type: "ADD_PAGE", pageId: id, props: { slug: uniqueSlug(schema, t), title: t } }], summary: `Thêm trang ${t}` };
}

/** Renaming the home page changes its title only (its route is always "/"); another page may also change its slug. */
export type PageSeo = { title?: string; description?: string; noindex?: boolean };
/** `seo` (Website drawer, M-047) is sent as given: the same UPDATE_PAGE, validated by the same slug rules as the builder rename dialog */
export function opsRenamePage(schema: PageSchema, pageId: string, title: string, slug?: string, seo?: PageSeo): { ops: SchemaOperation[]; summary: string } | { error: string } {
  const t = title.trim();
  const extra = seo ? { seo } : {};
  // the home page may keep an empty title (the site falls back to "Trang chủ") when only its SEO is saved
  if (pageId === HOME_ID && !t && seo) return { ops: [{ type: "UPDATE_PAGE", pageId: HOME_ID, props: extra }], summary: "Cập nhật SEO trang chủ" };
  if (!t) return { error: "Tên trang không được để trống." };
  if (pageId === HOME_ID) return { ops: [{ type: "UPDATE_PAGE", pageId: HOME_ID, props: { title: t, ...extra } }], summary: `Đổi tên trang chủ thành ${t}` };
  if (!schema.pages?.some((p) => p.id === pageId)) return { error: "Không tìm thấy trang." };
  const props: Record<string, unknown> = { title: t, ...extra };
  if (slug !== undefined) { const c = checkSlug(schema, slug, pageId); if (!c.ok) return { error: c.reason }; props.slug = slug; }
  return { ops: [{ type: "UPDATE_PAGE", pageId, props }], summary: `Đổi tên trang ${t}` };
}

export type RemoveImpact = { pageTitle: string; sections: number; navLinks: number; actionsPointingHere: string[]; message: string };

/** what deleting a page will take with it, so the confirm dialog can say it (the backend also drops the nav link of the removed page) */
export function removeImpact(schema: PageSchema, pageId: string, actions: { id: string; name?: string; type: string; pageRef?: string }[] = []): RemoveImpact | null {
  const p = schema.pages?.find((x) => x.id === pageId);
  if (!p) return null;
  const navLinks = (schema.site?.navigation ?? []).filter((l) => l.pageId === pageId).length;
  const pointing = actions.filter((a) => a.type === "NAVIGATE" && a.pageRef === pageId).map((a) => a.name || a.id);
  const parts = [`${p.sections.length} phần của trang`, ...(navLinks ? [`${navLinks} liên kết trong menu`] : [])];
  const warn = pointing.length ? ` Có ${pointing.length} hành động chuyển trang đang trỏ tới trang này (${pointing.join(", ")}); chúng sẽ bị hỏng cho tới khi sửa.` : "";
  return { pageTitle: p.title, sections: p.sections.length, navLinks, actionsPointingHere: pointing, message: `Xoá trang “${p.title}” sẽ xoá ${parts.join(" và ")}.${warn}` };
}

export function opsRemovePage(schema: PageSchema, pageId: string): { ops: SchemaOperation[]; summary: string } | { error: string } {
  if (pageId === HOME_ID) return { error: "Không thể xoá trang chủ." };
  const p = schema.pages?.find((x) => x.id === pageId);
  if (!p) return { error: "Không tìm thấy trang." };
  return { ops: [{ type: "REMOVE_PAGE", pageId }], summary: `Xoá trang ${p.title}` };
}

// -------------------------------------------------------------------------------------------------------------- navigation
export function opsSetNavigation(links: NavLink[]): { ops: SchemaOperation[]; summary: string } | { error: string } {
  if (links.length > MAX_NAV) return { error: `Menu tối đa ${MAX_NAV} liên kết.` };
  if (links.some((l) => !l.label.trim())) return { error: "Mỗi liên kết cần có nhãn." };
  return { ops: [{ type: "SET_NAVIGATION", value: links.map((l) => ({ ...l, label: l.label.trim() })) }], summary: "Cập nhật điều hướng" };
}

/** reorder one menu link (the menu order is real; the order of the page list in the document is not editable, see PAGE_REORDER) */
export function moveNavLink(links: NavLink[], from: number, to: number): NavLink[] {
  if (from < 0 || from >= links.length) return links;
  const t = Math.max(0, Math.min(links.length - 1, to));
  if (t === from) return links;
  const next = links.slice(); const [item] = next.splice(from, 1); next.splice(t, 0, item);
  return next;
}

export function addPageToMenu(links: NavLink[], page: PageNode, id: string): NavLink[] {
  if (links.some((l) => l.pageId === page.id)) return links;
  return [...links, { id, label: page.title, pageId: page.id }];
}

export const setHomeReadiness = (): Readiness => notReady("Máy chủ chưa có thao tác đặt trang chủ (trang chủ là phần gốc của tài liệu).");
export const reorderPagesReadiness = (): Readiness => notReady("Máy chủ chưa có thao tác đổi thứ tự trang. Bạn có thể đổi thứ tự menu điều hướng.");

// -------------------------------------------------------------------------------------------------------------- routing / 404
/** the one UPDATE_SITE for the 404 page (builder panel and Website drawer, M-047): empty fields fall back to the default text */
export function opsSetNotFound(title: string, message: string): { ops: SchemaOperation[]; summary: string } {
  return { ops: [{ type: "UPDATE_SITE", props: { notFound: { ...(title.trim() ? { title: title.trim() } : {}), ...(message.trim() ? { message: message.trim() } : {}) } } }], summary: "Cập nhật trang 404" };
}

export type RouteResult = { kind: "page"; page: PageNode } | { kind: "notfound"; title: string; message: string };

/** Resolves a public path the way the published site does: "/" = home, "/slug/" = page, anything else = the 404 page of the site. */
export function resolveRoute(schema: PageSchema, path: string): RouteResult {
  const clean = path.split(/[?#]/)[0].replace(/\/+$/, "").replace(/^\/+/, "");
  const pages = listPages(schema);
  const hit = pages.find((p) => p.slug === clean);
  if (hit) return { kind: "page", page: hit };
  const nf = schema.site?.notFound;
  return { kind: "notfound", title: nf?.title || "Không tìm thấy trang", message: nf?.message || "Trang bạn tìm không tồn tại hoặc đã được chuyển đi." };
}

/** Where a NAVIGATE action / menu link with this page id leads: a page, or nowhere (broken). */
export function pageExists(schema: PageSchema, pageId: string): boolean {
  return pageId === HOME_ID || !!schema.pages?.some((p) => p.id === pageId);
}

/** anchors the renderer emits per component type (lib/schema-preview.ts); a menu anchor needs a section that provides it on the page it is shown on */
export const ANCHOR_OF_TYPE: Readonly<Record<string, string>> = {
  Hero: "#top", ProductGrid: "#products", TechnologySection: "#technology", ComparisonBlock: "#comparison", Testimonials: "#testimonials", ContactForm: "#contact",
};
export function anchorsOnPage(sections: Section[]): Set<string> {
  return new Set(sections.map((s) => ANCHOR_OF_TYPE[s.type]).filter((a): a is string => !!a));
}
export type { SitePage };
