// @class: real-backend — E2E-ORG01: the Dynamic Organization against a REAL backend with `app.organization.persistence-enabled=true` (docs/parallel/c0/ORGANIZATION_API_CONTRACT_FOR_C5.md, D-C0-52). 25 cases, no mock, no SQL.
// Needs a C0-APPROVED isolated stack with ORGANIZATION_PERSISTENCE_ENABLED=true. On a default stack (flag OFF, the production default) every organization route answers 501 ORG_PERSISTENCE_NOT_AVAILABLE: the flow then records the FAIL-CLOSED
// evidence of the real server and the real Admin portal (cases 0a-0g) and ends BLOCKED(C0): it never reports PASS for cases it could not run, and it never enables the flag itself.
// Every case records REQUEST · EXPECTED · ACTUAL · HTTP · UI · SERVER in its check detail (readable in the JSON report). The tenant admin gets the six organization codes from the server (TENANT_ADMIN of the PRIMARY tenant): nothing is granted by a role label.
import { Blocked } from "../lib/report.mjs";
import { loginPortal, makeTenant, makeTenantUser, openPortal, watchApi } from "../lib/portals.mjs";
import { newPage, pageProblems, confirmCancel, confirmYes, waitConfirm } from "../lib/ui.mjs";
export const id = "E2E-ORG01", title = "Dynamic Organization on a real backend (flag ON): types, tree, depth, move, archive / restore, employees, memberships, positions, counts, limits, isolation, permissions (25 cases)";

const FAMILIES = ["organization-unit-types", "organization-units", "positions", "grades", "employees"];
const short = (v) => (typeof v === "string" ? v : JSON.stringify(v))?.slice(0, 140);

export async function run({ cfg, fx, browser, check }) {
  const A = await makeTenant(fx, "orgA"), B = await makeTenant(fx, "orgB");
  const adminA = await makeTenantUser(fx, cfg, A.id, "orgAadmin", { tenantRole: "TENANT_ADMIN", workspaceId: A.workspaceId, workspaceRole: "WORKSPACE_ADMIN" });
  const adminB = await makeTenantUser(fx, cfg, B.id, "orgBadmin", { tenantRole: "TENANT_ADMIN" });
  const memberA = await makeTenantUser(fx, cfg, A.id, "orgAmember", { tenantRole: "MEMBER", workspaceId: A.workspaceId, workspaceRole: "VIEWER" });
  const sa = adminA.session, sb = adminB.session, sm = memberA.session, sys = fx.sessions.admin;
  const T = `/admin/tenants/${A.id}`, TB = `/admin/tenants/${B.id}`;
  const me = (await sa.get("/auth/me")).body;
  check.ok("[setup] the tenant admin's /auth/me lists the six organization codes for the PRIMARY tenant (the server grants them; no role label is read by the frontend)", ["ORG_STRUCTURE_VIEW", "ORG_STRUCTURE_MANAGE", "EMPLOYEE_VIEW", "EMPLOYEE_MANAGE", "POSITION_GRADE_VIEW", "POSITION_GRADE_MANAGE"].every((c) => me?.permissions?.includes(c)), short(me?.permissions), "http");

  // ------------------------------------------------------------------------------------------------------------------------------------------------ the flag
  const probe = await sa.get(`${T}/organization-units`);
  if (probe.status === 501) {
    check.ok("0a [OFF] every organization route family answers 501 ORG_PERSISTENCE_NOT_AVAILABLE for a tenant admin (authenticated and authorized)", (await Promise.all(FAMILIES.map((f) => sa.get(`${T}/${f}`)))).every((r) => r.status === 501 && r.body?.code === "ORG_PERSISTENCE_NOT_AVAILABLE"), "", "http");
    const w = await sa.post(`${T}/organization-unit-types`, { name: "X", code: "x" });
    check.ok("0b [OFF] a WRITE answers 501 too and nothing was created", w.status === 501 && w.body?.code === "ORG_PERSISTENCE_NOT_AVAILABLE", `status=${w.status} ${w.body?.code}`, "http");
    const m = await sm.get(`${T}/organization-units`);
    check.ok("0c [OFF] authorization comes BEFORE the 501: a plain member is refused (403), not told about the feature flag", m.status === 403, `status=${m.status} ${m.body?.code}`, "http");
    const page = await newPage(browser); const bad = watchApi(page);
    await loginPortal(page, cfg, "admin", adminA.username, adminA.password);
    await openPortal(page, cfg, "admin", "/organization");
    const er = page.getByTestId("org-error");
    check.ok("0d [OFF] the real Admin portal says the organization is NOT AVAILABLE (its own state, 'chưa được bật trên máy chủ'), shows no tree and no empty-state, and offers 'Kiểm tra lại' only", (await er.getAttribute("data-kind")) === "unavailable-feature" && /chưa được bật trên máy chủ/.test(await er.innerText()) && (await page.getByTestId("org-tree").count()) === 0 && (await page.getByTestId("org-empty").count()) === 0, "", "ui");
    await openPortal(page, cfg, "admin", "/employees");
    check.ok("0e [OFF] the employee directory: the same fail-closed state, no table, no fallback to the member list", (await page.getByTestId("emp-error").getAttribute("data-kind")) === "unavailable-feature" && (await page.getByTestId("emp-table").count()) === 0 && !bad.some((b) => /\/members/.test(b) && /\/employees/.test(b)), bad.join(" | "), "ui");
    const keys = await page.evaluate(() => Object.keys(localStorage).concat(Object.keys(sessionStorage)));
    check.ok("0f [OFF] nothing about the organization was kept in the browser (no localStorage / sessionStorage entry): no local fallback", !keys.some((k) => /org|employee|unit/i.test(k)), keys.join(","), "ui");
    const own = pageProblems(page).filter((x) => !/Failed to load resource: the server responded with a status of 501/.test(x));   // the browser logs the EXPECTED 501 answers itself
    check.ok("0g no console error / uncaught exception while the feature was off (the browser's own log of the expected 501 answers excepted)", own.length === 0, own.slice(0, 2).join(" | "), "ui");
    await page.context().close();
    throw new Blocked("C0", "WAITING_FOR_C0_FLAG_ON_STACK: this stack runs with ORGANIZATION_PERSISTENCE_ENABLED=false (the production default), so the 25 flag-ON cases did not run. Cases 0a-0g above are REAL_BACKEND evidence of the fail-closed behaviour. Provide an isolated, C0-approved stack with the flag true and re-run E2E-ORG01.", "D-C0-52");
  }
  check.ok("0 [ON] the organization store answers (200) for the tenant admin: the flag is ON on this stack", probe.status === 200, `status=${probe.status} ${probe.body?.code ?? ""}`, "http");

  // case recorder: REQUEST · EXPECTED · ACTUAL · HTTP · UI · SERVER
  const rec = (n, name, ok, o) => check.ok(`${String(n).padStart(2, "0")} ${name}`, ok, `REQUEST ${o.request} · EXPECTED ${o.expected} · ACTUAL ${o.actual} · HTTP ${o.http ?? "-"} · UI ${o.ui ?? "-"} · SERVER ${o.server ?? "-"}`, o.kind ?? "http");
  const post = (s, p, b) => s.post(`${T}${p}`, b), get = (s, p) => s.get(`${T}${p}`), patch = (s, p, b) => s.patch(`${T}${p}`, b);
  const typeOf = async (code, rules = {}) => post(sa, "/organization-unit-types", { name: code, code, icon: "folder", rules });

  // ---- 01 types
  const div = await typeOf("division"); const dept = await typeOf("dept", { allowedParentTypeIds: [div.body?.id] }); const team = await typeOf("team", { allowedParentTypeIds: [dept.body?.id] });
  const dup = await typeOf("division");
  rec(1, "unit types with placement rules: division (any), dept (under division), team (under dept, tenant-defined); a duplicate code is refused", [div, dept, team].every((r) => r.status === 201 && r.body?.version === 0) && dup.status === 409 && dup.body?.code === "ORG_UNIT_TYPE_CODE_TAKEN", { request: "POST organization-unit-types ×4", expected: "201 ×3 (version 0), 409 ORG_UNIT_TYPE_CODE_TAKEN", actual: `${[div, dept, team].map((r) => r.status)} / ${dup.status} ${dup.body?.code}`, http: "201/409", server: short(div.body) });
  const mk = (typeId, parentId, name, code) => post(sa, "/organization-units", { typeId, parentId, name, code });
  // ---- 02 tree
  const R = await mk(div.body.id, null, "Khối Công nghệ", "tech"); const D = await mk(dept.body.id, R.body?.id, "Mobile", "mobile"); const Tm = await mk(team.body.id, D.body?.id, "Flutter Team", "flutter");
  const tree = (await get(sa, "/organization-units?format=tree")).body; const flat = (await get(sa, "/organization-units?format=flat")).body;
  const node = tree?.find?.((n) => n.unit.id === R.body?.id);
  rec(2, "the tree: nested nodes {unit, children, directMemberCount, subtreeEmployeeCount}; flat has parentId; the code is stored UPPER-CASE; versions start at 0", [R, D, Tm].every((r) => r.status === 201) && R.body.code === "TECH" && node?.children?.[0]?.children?.[0]?.unit?.id === Tm.body?.id && Array.isArray(flat) && flat.find((u) => u.id === Tm.body.id)?.parentId === D.body.id && R.body.version === 0, { request: "POST ×3, GET tree, GET flat", expected: "201; nested 3 levels; code TECH; parentId in flat", actual: `${R.status}/${D.status}/${Tm.status} code=${R.body?.code}`, http: "201,200", server: short(node?.unit) });
  // ---- 03 arbitrary depth
  const deepType = await post(sa, "/organization-unit-types", { name: "level", code: "level", icon: "layers", rules: {} }); let parent = R.body.id, deepest = null, depthOk = true;
  for (let i = 0; i < 12; i++) { const u = await mk(deepType.body.id, parent, `L${i}`, `L${i}`); depthOk = depthOk && u.status === 201; parent = u.body?.id; deepest = u; }
  const detail = (await get(sa, `/organization-units/${deepest.body?.id}`)).body;
  rec(3, "arbitrary depth: a chain of 12 nested units is accepted (no fixed hierarchy) and the detail's path lists every ancestor", depthOk && (detail?.path?.length ?? 0) >= 13, { request: "POST ×12 nested", expected: "201 each; path length >= 13", actual: `path=${detail?.path?.length}`, http: "201", server: `${detail?.path?.map?.((p) => p.name).join(" > ")}`.slice(0, 120) });
  // ---- 04 type rules
  const rootDept = await mk(dept.body.id, null, "Phòng gốc", "rootdept"); const teamUnderDiv = await mk(team.body.id, R.body.id, "Team lỗi", "badteam");
  rec(4, "type rules are enforced by the server: dept as a root → 409 ORG_TYPE_RULE_VIOLATION (ROOT_NOT_ALLOWED); team under a division → PARENT_TYPE_NOT_ALLOWED", rootDept.status === 409 && rootDept.body?.details?.reason === "ROOT_NOT_ALLOWED" && teamUnderDiv.status === 409 && teamUnderDiv.body?.details?.reason === "PARENT_TYPE_NOT_ALLOWED", { request: "POST dept root, POST team under division", expected: "409 ROOT_NOT_ALLOWED / PARENT_TYPE_NOT_ALLOWED", actual: `${rootDept.status} ${rootDept.body?.details?.reason} / ${teamUnderDiv.status} ${teamUnderDiv.body?.details?.reason}`, http: "409" });
  // ---- 05 max depth (the backend is the authority)
  const capped = await post(sa, "/organization-unit-types", { name: "capped", code: "capped", icon: "folder", rules: { maxDepth: 2 } });
  const c1 = await mk(capped.body.id, null, "Cap 1", "cap1"), c2 = await mk(capped.body.id, c1.body?.id, "Cap 2", "cap2"), c3 = await mk(capped.body.id, c2.body?.id, "Cap 3", "cap3");
  rec(5, "max depth is the BACKEND's decision (the type's rules.maxDepth): level 3 of a type capped at 2 → 409 ORG_TYPE_RULE_VIOLATION MAX_DEPTH, while levels 1-2 are fine", c1.status === 201 && c2.status === 201 && c3.status === 409 && c3.body?.details?.reason === "MAX_DEPTH", { request: "POST capped ×3", expected: "201,201,409 MAX_DEPTH", actual: `${c1.status},${c2.status},${c3.status} ${c3.body?.details?.reason}`, http: "409" });
  // ---- 06 edit + stale version
  const e1 = await patch(sa, `/organization-units/${Tm.body.id}`, { name: "Flutter Squad", expectedVersion: 0 }); const e2 = await patch(sa, `/organization-units/${Tm.body.id}`, { name: "Stale", expectedVersion: 0 });
  rec(6, "optimistic versions: an edit with the current version → 200 (version 1); the same edit with the stale version → 409 VERSION_CONFLICT carrying details.currentVersion", e1.status === 200 && e1.body?.version === 1 && e2.status === 409 && e2.body?.code === "VERSION_CONFLICT" && e2.body?.details?.currentVersion === 1, { request: "PATCH expectedVersion 0 ×2", expected: "200 v1, 409 VERSION_CONFLICT currentVersion 1", actual: `${e1.status} v${e1.body?.version}, ${e2.status} ${e2.body?.code} cv=${e2.body?.details?.currentVersion}`, http: "200/409", server: short({ name: e1.body?.name }) });
  // ---- 07 code uniqueness among siblings
  const sib1 = await mk(dept.body.id, R.body.id, "Web", "web"), sib2 = await mk(dept.body.id, R.body.id, "Web 2", "WEB"), other = await mk(div.body.id, null, "Khối Nhân sự", "web");
  rec(7, "unit code is unique among NON-archived siblings (case-insensitive: web = WEB → 409 ORG_UNIT_CODE_TAKEN) but may repeat under another parent (roots are siblings of each other)", sib1.status === 201 && sib2.status === 409 && sib2.body?.code === "ORG_UNIT_CODE_TAKEN" && other.status === 201, { request: "POST web, WEB (same parent), web (root)", expected: "201, 409 ORG_UNIT_CODE_TAKEN, 201", actual: `${sib1.status}, ${sib2.status} ${sib2.body?.code}, ${other.status}`, http: "201/409" });
  // ---- 08 move
  const mv = await post(sa, `/organization-units/${Tm.body.id}/move`, { newParentId: sib1.body.id, expectedVersion: 1 }); const mvTree = (await get(sa, "/organization-units?format=flat")).body;
  const noKey = await post(sa, `/organization-units/${other.body.id}/move`, { expectedVersion: 0 }); const toRoot = await post(sa, `/organization-units/${sib1.body.id}/move`, { newParentId: null, expectedVersion: 0 });
  rec(8, "move / reparent: the subtree follows; `newParentId` is REQUIRED (absent key → 400, never a silent move); null = root (here refused for a dept by its type rule)", mv.status === 200 && mvTree?.find?.((u) => u.id === Tm.body.id)?.parentId === sib1.body.id && noKey.status === 400 && toRoot.status === 409, { request: "POST move (parent), move (no key), move (null)", expected: "200 parent changed, 400, 409 ROOT_NOT_ALLOWED", actual: `${mv.status}, ${noKey.status}, ${toRoot.status} ${toRoot.body?.details?.reason}`, http: "200/400/409", server: `parentId=${mvTree?.find?.((u) => u.id === Tm.body.id)?.parentId === sib1.body.id}` });
  // ---- 09 cycle
  const cyc = await post(sa, `/organization-units/${R.body.id}/move`, { newParentId: Tm.body.id, expectedVersion: 0 });
  rec(9, "a cycle is refused by the server: moving a unit under its own descendant → 409 ORG_CYCLE", cyc.status === 409 && cyc.body?.code === "ORG_CYCLE", { request: "POST move root under its descendant", expected: "409 ORG_CYCLE", actual: `${cyc.status} ${cyc.body?.code}`, http: "409" });
  // ---- 10 positions / grades
  const p1 = await post(sa, "/positions", { name: "Kỹ sư", code: "ENG" }), p2 = await post(sa, "/positions", { name: "Trùng", code: "eng" }), g1 = await post(sa, "/grades", { name: "Senior", code: "SR", rank: 3 }), g2 = await post(sa, "/grades", { name: "Junior", code: "JR", rank: 1 });
  const pd = await post(sa, `/positions/${p1.body?.id}/disable`, { expectedVersion: 0 }); const pe = await post(sa, `/positions/${p1.body?.id}/enable`, { expectedVersion: 1 });
  rec(10, "positions and grades: created; a code that differs only by case is refused (409 POSITION_CODE_TAKEN, also against disabled ones); disable / enable bump the version", p1.status === 201 && p2.status === 409 && p2.body?.code === "POSITION_CODE_TAKEN" && g1.status === 201 && g2.status === 201 && pd.status === 200 && pd.body?.active === false && pe.status === 200 && pe.body?.active === true && pe.body?.version === 2, { request: "POST positions ×2, grades ×2, disable, enable", expected: "201,409,201,201,200 inactive,200 active v2", actual: `${p1.status},${p2.status},${g1.status},${g2.status},${pd.status},${pe.status} v${pe.body?.version}`, http: "201/409/200" });
  // ---- 11 employee in ONE request
  const unamePrefix = `e2e-${fx.runId}-emp`.toLowerCase(); const mkEmp = (n, body = {}) => post(sa, "/employees", { username: `${unamePrefix}${n}`, displayName: `Nhân viên ${n}`, tenantRole: "MEMBER", organizationMemberships: [{ organizationUnitId: Tm.body.id, primary: true, positions: [{ positionId: p1.body.id, gradeId: g1.body.id, primary: true }] }], ...body });
  const emp1 = await mkEmp(1); if (emp1.body?.employee?.userId) fx.created.users.push(emp1.body.employee.userId);
  rec(11, "an employee is created with membership + position + grade in ONE request: 201 {employee, activation}; the account is NOT activated; no password is returned", emp1.status === 201 && emp1.body?.employee?.organizationMemberships?.length === 1 && emp1.body?.employee?.positions?.length === 1 && emp1.body?.employee?.positions?.[0]?.gradeId === g1.body.id && emp1.body?.employee?.accountActivated === false && !!emp1.body?.activation?.token && !/password/i.test(JSON.stringify(emp1.body)), { request: "POST employees {username, memberships[positions[]]}", expected: "201 with the nested records, activation link, accountActivated=false", actual: `${emp1.status} m=${emp1.body?.employee?.organizationMemberships?.length} p=${emp1.body?.employee?.positions?.length}`, http: "201", server: short({ activated: emp1.body?.employee?.accountActivated }) });
  // ---- 12 atomicity
  const bad = await post(sa, "/employees", { username: `${unamePrefix}x`, displayName: "Atomic", tenantRole: "MEMBER", organizationMemberships: [{ organizationUnitId: Tm.body.id, positions: [{ positionId: "00000000-0000-0000-0000-0000000000aa" }] }] });
  const again = await post(sa, "/employees", { username: `${unamePrefix}x`, displayName: "Atomic", tenantRole: "MEMBER" }); if (again.body?.employee?.userId) fx.created.users.push(again.body.employee.userId);
  rec(12, "atomicity: a create whose nested position does not exist → 404 POSITION_NOT_FOUND and NOTHING is created (the same username is free afterwards)", bad.status === 404 && bad.body?.code === "POSITION_NOT_FOUND" && again.status === 201, { request: "POST employees (bad position), POST employees (same username)", expected: "404 POSITION_NOT_FOUND, then 201", actual: `${bad.status} ${bad.body?.code}, ${again.status}`, http: "404/201" });
  // ---- 13 memberships (several, one primary)
  const uid = emp1.body.employee.userId; const m2 = await post(sa, `/employees/${uid}/organization-memberships`, { organizationUnitId: D.body.id, relationType: "manager", primary: true }); const mdup = await post(sa, `/employees/${uid}/organization-memberships`, { organizationUnitId: D.body.id });
  const list13 = (await get(sa, `/employees/${uid}/organization-memberships`)).body; const firstM = list13?.find?.((m) => m.organizationUnitId === Tm.body.id);
  const demote = await patch(sa, `/employees/${uid}/organization-memberships/${m2.body?.id}`, { primary: false, expectedVersion: m2.body?.version });
  rec(13, "several memberships, exactly ONE primary: a second membership with primary=true atomically demotes the first; primary=false is refused (400); a duplicate unit → 409 ORG_MEMBERSHIP_EXISTS; the relation is stored UPPER-CASE", m2.status === 201 && m2.body?.relationType === "MANAGER" && m2.body?.primary === true && list13?.filter?.((m) => m.primary).length === 1 && firstM?.primary === false && demote.status === 400 && mdup.status === 409 && mdup.body?.code === "ORG_MEMBERSHIP_EXISTS", { request: "POST membership (primary), POST again, PATCH primary=false", expected: "201 MANAGER primary; one primary; 400; 409", actual: `${m2.status} ${m2.body?.relationType}; primaries=${list13?.filter?.((m) => m.primary).length}; ${demote.status}; ${mdup.status} ${mdup.body?.code}`, http: "201/400/409", server: short(list13?.map?.((m) => [m.organizationUnitId === D.body.id ? "D" : "T", m.primary])) });
  // ---- 14 positions held within a membership
  const heldDup = await post(sa, `/employees/${uid}/positions`, { membershipId: firstM?.id, positionId: p1.body.id }); const held = (await get(sa, `/employees/${uid}/positions`)).body?.[0];
  const rmBlocked = await sa.del(`${T}/employees/${uid}/organization-memberships/${firstM?.id}?expectedVersion=${firstM?.version}`);
  const rmPos = await sa.del(`${T}/employees/${uid}/positions/${held?.id}?expectedVersion=${held?.version}`);
  const fm2 = (await get(sa, `/employees/${uid}/organization-memberships`)).body?.find?.((m) => m.id === firstM?.id); const rmOk = await sa.del(`${T}/employees/${uid}/organization-memberships/${firstM?.id}?expectedVersion=${fm2?.version}`);
  rec(14, "a position is held WITHIN a membership: a duplicate → 409 POSITION_ASSIGNMENT_EXISTS; ending the membership while a position is held → 409 EMPLOYEE_ORG_HAS_POSITIONS; after removing the position the membership can end", heldDup.status === 409 && heldDup.body?.code === "POSITION_ASSIGNMENT_EXISTS" && rmBlocked.status === 409 && rmBlocked.body?.code === "EMPLOYEE_ORG_HAS_POSITIONS" && rmPos.status === 200 && rmOk.status === 200, { request: "POST position (dup), DELETE membership, DELETE position, DELETE membership", expected: "409, 409, 200, 200", actual: `${heldDup.status} ${heldDup.body?.code}, ${rmBlocked.status} ${rmBlocked.body?.code}, ${rmPos.status}, ${rmOk.status}`, http: "409/200" });
  // ---- 15 counts: direct vs DISTINCT subtree
  const emp2 = await mkEmp(2, { organizationMemberships: [{ organizationUnitId: Tm.body.id, primary: true }, { organizationUnitId: sib1.body.id }] }); if (emp2.body?.employee?.userId) fx.created.users.push(emp2.body.employee.userId);
  const ct = (await get(sa, "/organization-units?format=tree")).body; const find = (nodes, id) => { for (const n of nodes ?? []) { if (n.unit.id === id) return n; const c = find(n.children, id); if (c) return c; } return null; };
  const nWeb = find(ct, sib1.body.id), nTech = find(ct, R.body.id); const dWeb = (await get(sa, `/organization-units/${sib1.body.id}`)).body;
  rec(15, "counts: directMemberCount = ACTIVE memberships on exactly that unit; subtreeEmployeeCount = DISTINCT employees (an employee in two units of the branch counts ONCE); the detail endpoint agrees with the tree", nWeb?.directMemberCount === 1 && nWeb?.subtreeEmployeeCount === 1 && dWeb?.directMemberCount === nWeb?.directMemberCount && dWeb?.subtreeEmployeeCount === nWeb?.subtreeEmployeeCount && nTech?.subtreeEmployeeCount >= 1, { request: "POST employee in Flutter + Web, GET tree, GET unit", expected: "Web direct 1, subtree 1 (the person is also in Flutter below it: counted once)", actual: `web direct=${nWeb?.directMemberCount} subtree=${nWeb?.subtreeEmployeeCount}; tech subtree=${nTech?.subtreeEmployeeCount}`, http: "200", server: short({ web: [nWeb?.directMemberCount, nWeb?.subtreeEmployeeCount], detail: [dWeb?.directMemberCount, dWeb?.subtreeEmployeeCount] }) });
  // ---- 16 enable / disable
  const before = find((await get(sa, "/organization-units?format=tree")).body, Tm.body.id)?.directMemberCount; const dis = await sa.post(`${T}/employees/${emp2.body.employee.userId}/disable`, {}); const after = find((await get(sa, "/organization-units?format=tree")).body, Tm.body.id)?.directMemberCount; const en = await sa.post(`${T}/employees/${emp2.body.employee.userId}/enable`, {}); const back = find((await get(sa, "/organization-units?format=tree")).body, Tm.body.id)?.directMemberCount;
  rec(16, "disabling an employee removes them from the counts; enabling brings them back (the membership is kept)", dis.status === 200 && dis.body?.active === false && after === before - 1 && en.status === 200 && back === before, { request: "POST disable, GET tree, POST enable, GET tree", expected: "direct count n → n-1 → n", actual: `${before} → ${after} → ${back}`, http: "200", server: `active=${dis.body?.active}` });
  // ---- 17 directory + limits
  const q1 = await get(sa, "/employees?q=a"), q2 = await get(sa, `/employees?q=${encodeURIComponent(unamePrefix)}&page=0&size=20`), s101 = await get(sa, "/employees?size=101"), off = await get(sa, "/employees?page=501&size=20"), offOk = await get(sa, "/employees?page=500&size=20"), fU = await get(sa, `/employees?organizationUnitId=${R.body.id}&includeDescendants=true`), fN = await get(sa, `/employees?organizationUnitId=${R.body.id}&includeDescendants=false`);
  rec(17, "the directory: q needs 2 characters (400 QUERY_TOO_SHORT); size 101 → 400; page*size 10 020 → 400 OFFSET_TOO_LARGE; page*size = 10 000 → 200; a unit filter with descendants finds employees that a direct-only filter does not", q1.status === 400 && q1.body?.code === "QUERY_TOO_SHORT" && q2.status === 200 && q2.body?.total >= 2 && s101.status === 400 && off.status === 400 && off.body?.code === "OFFSET_TOO_LARGE" && offOk.status === 200 && fU.body?.total > fN.body?.total, { request: "GET employees (q=a, size=101, page=501, page=500, unit ±descendants)", expected: "400,200,400,400 OFFSET_TOO_LARGE,200, with>without", actual: `${q1.status} ${q1.body?.code},${q2.status},${s101.status},${off.status} ${off.body?.code},${offOk.status}, ${fU.body?.total}>${fN.body?.total}`, http: "400/200" });
  // ---- 18 archive blocks
  const aKids = await post(sa, `/organization-units/${R.body.id}/archive`, { expectedVersion: 0 }); const aMem = await post(sa, `/organization-units/${Tm.body.id}/archive`, { expectedVersion: (await get(sa, `/organization-units/${Tm.body.id}`)).body?.unit?.version });
  rec(18, "archive is refused with the SERVER's reason: a unit with active children → 409 ORG_UNIT_HAS_CHILDREN; a unit with active members → 409 ORG_UNIT_HAS_MEMBERS (nothing cascades)", aKids.status === 409 && aKids.body?.code === "ORG_UNIT_HAS_CHILDREN" && aMem.status === 409 && aMem.body?.code === "ORG_UNIT_HAS_MEMBERS", { request: "POST archive (root), POST archive (unit with members)", expected: "409 HAS_CHILDREN, 409 HAS_MEMBERS", actual: `${aKids.status} ${aKids.body?.code}, ${aMem.status} ${aMem.body?.code}`, http: "409" });
  // ---- 19 archive / restore
  const leaf = await mk(dept.body.id, R.body.id, "Tạm", "tmp"); const arch = await post(sa, `/organization-units/${leaf.body.id}/archive`, { expectedVersion: 0 });
  const hidden = !(await get(sa, "/organization-units?format=flat")).body?.some?.((u) => u.id === leaf.body.id), shown = (await get(sa, "/organization-units?format=flat&includeArchived=true")).body?.find?.((u) => u.id === leaf.body.id);
  const clash = await mk(dept.body.id, R.body.id, "Tạm 2", "tmp"); const rcode = await post(sa, `/organization-units/${leaf.body.id}/restore`, { expectedVersion: arch.body?.version });
  const rename = await patch(sa, `/organization-units/${clash.body?.id}`, { code: "tmp2", expectedVersion: 0 }); const rok = await post(sa, `/organization-units/${leaf.body.id}/restore`, { expectedVersion: arch.body?.version });
  rec(19, "archive + restore: archive → active=false + archivedAt, hidden by default and listed with includeArchived; restoring while another unit holds the code → 409 RESTORE_CONFLICT (CODE_TAKEN); after the rename the restore succeeds", arch.status === 200 && arch.body?.active === false && !!arch.body?.archivedAt && hidden && shown?.active === false && clash.status === 201 && rcode.status === 409 && rcode.body?.code === "RESTORE_CONFLICT" && rcode.body?.details?.reason === "CODE_TAKEN" && rename.status === 200 && rok.status === 200 && rok.body?.active === true, { request: "POST archive, GET flat ±archived, POST same code, POST restore ×2", expected: "200 archived; hidden/shown; 409 RESTORE_CONFLICT CODE_TAKEN; 200", actual: `${arch.status}; ${hidden}/${shown?.active}; ${rcode.status} ${rcode.body?.details?.reason}; ${rok.status}`, http: "200/409" });
  // ---- 20 no hard delete
  const del = await sa.del(`${T}/organization-units/${leaf.body.id}`);
  rec(20, "there is NO hard delete: DELETE of a unit is not a success (405 / 404)", del.status === 405 || del.status === 404, { request: "DELETE organization-units/{id}", expected: "405 or 404", actual: `${del.status}`, http: String(del.status) });
  // ---- 21 foreign tenant
  const foreignUnit = await sb.get(`${T}/organization-units/${R.body.id}`), crossRead = await sb.get(`${T}/organization-units`), mine = await sa.get(`${TB}/organization-units`), idUnderB = await sb.get(`${TB}/organization-units/${R.body.id}`);
  rec(21, "tenant isolation: another company's admin is refused on THIS company's routes (403/404, never 200); this admin is refused on the other company's routes; a unit id of A under B's path is 404 ORG_UNIT_NOT_FOUND (disclosure-safe)", [foreignUnit, crossRead, mine].every((r) => r.status === 403 || r.status === 404) && idUnderB.status === 404 && idUnderB.body?.code === "ORG_UNIT_NOT_FOUND", { request: "GET A's unit as B's admin; GET A's list as B; GET B's list as A; GET A's unit id under B's path", expected: "403/404 ×3, 404 ORG_UNIT_NOT_FOUND", actual: `${foreignUnit.status},${crossRead.status},${mine.status},${idUnderB.status} ${idUnderB.body?.code}`, http: "403/404" });
  // ---- 22 permissions: relation / position / grade authorize nothing
  const asMember = await Promise.all(FAMILIES.map((f) => sm.get(`${T}/${f}`))); const memberWrite = await sm.post(`${T}/organization-units`, { typeId: div.body.id, name: "Không được", code: "nope" });
  const lab = await post(sa, `/employees/${memberA.id}/organization-memberships`, { organizationUnitId: Tm.body.id, relationType: "HEAD", primary: true }); const lp = await post(sa, `/employees/${memberA.id}/positions`, { membershipId: lab.body?.id, positionId: p1.body.id, gradeId: g1.body.id });
  const afterLabel = await Promise.all([sm.get(`${T}/organization-units`), sm.post(`${T}/organization-units`, { typeId: div.body.id, name: "HEAD không phải quyền", code: "head" }), sm.post(`${T}/organization-units/${Tm.body.id}/archive`, { expectedVersion: 9 })]);
  rec(22, "a plain member holds NO organization code: every family answers 403; and giving them the relation HEAD, a position and a grade changes NOTHING (still 403): relation, position and grade authorize nothing", asMember.every((r) => r.status === 403) && memberWrite.status === 403 && lab.status === 201 && lp.status === 201 && afterLabel.every((r) => r.status === 403), { request: "member GET ×5, POST unit; then HEAD relation + position + grade; GET/POST/archive again", expected: "403 everywhere, before and after the labels", actual: `${asMember.map((r) => r.status)} / ${memberWrite.status} / labels ${lab.status},${lp.status} / ${afterLabel.map((r) => r.status)}`, http: "403" });
  // ---- 23 suspended tenant
  const susp = await sys.patch(`/admin/tenants/${A.id}/status`, { status: "SUSPENDED" }); const rd = await get(sa, "/organization-units"), wr = await mk(div.body.id, null, "Khối khi khóa", "susp"); const emp3 = await post(sa, "/employees", { username: `${unamePrefix}s`, displayName: "Khóa", tenantRole: "MEMBER" });
  await sys.patch(`/admin/tenants/${A.id}/status`, { status: "ACTIVE" }); const wr2 = await mk(div.body.id, null, "Khối khi mở", "susp");
  rec(23, "a SUSPENDED company is read-only for the organization: reads stay 200, writes (unit, employee) → 403 TENANT_SUSPENDED; after the unlock the same write succeeds", susp.status === 200 && rd.status === 200 && wr.status === 403 && wr.body?.code === "TENANT_SUSPENDED" && emp3.status === 403 && wr2.status === 201, { request: "PATCH tenant SUSPENDED; GET, POST unit, POST employee; PATCH ACTIVE; POST unit", expected: "200,200,403 TENANT_SUSPENDED,403,201", actual: `${susp.status},${rd.status},${wr.status} ${wr.body?.code},${emp3.status},${wr2.status}`, http: "403" });
  // ---- 24 contention (503 ORG_STRUCTURE_BUSY): provoked, NOT guaranteed
  const burst = await Promise.all(Array.from({ length: 16 }, (_, i) => mk(deepType.body.id, R.body.id, `Burst ${i}`, `burst${i}`)));
  const busy = burst.filter((r) => r.status === 503), okN = burst.filter((r) => r.status === 201).length;
  const shape = busy.every((r) => r.body?.code === "ORG_STRUCTURE_BUSY" && r.body?.details?.retryable === true && Number(r.headers?.get?.("retry-after")) >= 1);
  rec(24, busy.length ? "structural contention produced 503 ORG_STRUCTURE_BUSY: body details {retryable, retryAfterSeconds} + Retry-After header; every other request succeeded and nothing else failed" : "16 parallel structural writes: all serialised by the lock (no 503 was provoked on this host: the busy path is covered by the harness, NOT proven here)", burst.every((r) => r.status === 201 || r.status === 503) && shape, { request: "16 parallel POST organization-units", expected: "201 or 503 ORG_STRUCTURE_BUSY (Retry-After >= 1)", actual: `201×${okN} 503×${busy.length}`, http: "201/503" });

  // ---- 25 the REAL Admin portal (UI): tree, counts, archive dialog, directory
  const page = await newPage(browser); const badApi = watchApi(page);
  await loginPortal(page, cfg, "admin", adminA.username, adminA.password);
  // the login page probes GET /auth/me BEFORE any session exists: 401 is the canonical answer. Only that exact request, only before the login finished, is set aside (and asserted below); any other, and any 401 after the login, still counts.
  const PRE_AUTH_PROBE = /^GET \S*\/auth\/me → 401$/; const preAuth = badApi.splice(0); const preAuthUnexpected = preAuth.filter((b) => !PRE_AUTH_PROBE.test(b));
  await openPortal(page, cfg, "admin", "/organization");
  const techSummary = (await page.getByTestId(`counts:${R.body.id}`).innerText().catch(() => ""));
  const apiTech = find((await get(sa, "/organization-units?format=tree")).body, R.body.id);
  check.ok("25a UI: the tree renders the company's own units and BOTH counts as labelled by the screen ('trực tiếp' / 'cả nhánh') equal the API's directMemberCount / subtreeEmployeeCount", (await page.getByTestId("org-tree").count()) === 1 && new RegExp(`${apiTech.directMemberCount} trực tiếp`).test(techSummary) && new RegExp(`${apiTech.subtreeEmployeeCount} cả nhánh`).test(techSummary), `REQUEST open /admin/organization · EXPECTED ${apiTech.directMemberCount}/${apiTech.subtreeEmployeeCount} · ACTUAL ${techSummary} · UI tree · SERVER ${short([apiTech.directMemberCount, apiTech.subtreeEmployeeCount])}`, "ui");
  await page.getByTestId("org-add-root").click(); await page.getByTestId("unit-name").fill("Khối UI"); await page.getByTestId("unit-code").fill("ui1"); await page.getByTestId("unit-dialog").locator("select.srOnly").first().selectOption(div.body.id);
  const created = page.waitForResponse((r) => r.request().method() === "POST" && /\/organization-units$/.test(new URL(r.url()).pathname), { timeout: 15_000 }); await page.getByTestId("unit-submit").click(); const cr = await created; const crBody = cr.request().postDataJSON();
  check.ok("25b UI: creating a unit through the screen sends ONE POST with typeId, parentId null, name, code (no tenant in the body) and the server answers 201", cr.status() === 201 && crBody.typeId === div.body.id && crBody.parentId === null && crBody.code === "ui1" && !("tenantId" in crBody), `REQUEST ${short(crBody)} · EXPECTED 201 · ACTUAL ${cr.status()} · HTTP ${cr.status()} · UI dialog closed · SERVER code=${(await cr.json()).code}`, "http");
  const uiUnit = (await get(sa, "/organization-units?format=flat")).body?.find?.((u) => u.code === "UI1"); await page.getByTestId(`node:${uiUnit?.id}`).click();
  const T_ARCH = /Lưu trữ/; await page.getByTestId("org-archive").click(); await waitConfirm(page, T_ARCH); await confirmCancel(page, T_ARCH);
  const stillActive = (await get(sa, `/organization-units/${uiUnit?.id}`)).body?.unit?.active;
  const archived = page.waitForResponse((r) => r.request().method() === "POST" && /\/archive$/.test(new URL(r.url()).pathname), { timeout: 15_000 }); await page.getByTestId("org-archive").click(); await waitConfirm(page, T_ARCH); await confirmYes(page, T_ARCH, "Lưu trữ đơn vị"); const ar = await archived;
  const nowArch = (await get(sa, `/organization-units/${uiUnit?.id}`)).body?.unit;
  check.ok("25c UI: the archive confirmation is IN-APP: cancel sends nothing (the unit stays active on the server); confirm archives it (POST …/archive 200) and the server holds active=false", stillActive === true && ar.status() === 200 && nowArch?.active === false && !!nowArch?.archivedAt, `REQUEST cancel, then confirm · EXPECTED active→archived · ACTUAL ${stillActive} → ${nowArch?.active} · HTTP ${ar.status()} · UI in-app dialog · SERVER ${short({ active: nowArch?.active, archivedAt: nowArch?.archivedAt })}`, "persistence");
  // 25d. Lifecycle: case 14 ENDED emp1's Flutter membership and its position on purpose, so the active directory must show only what is still active. A second employee that this step creates and never ends proves that a persisted unit / position / grade IS listed.
  const empLive = await mkEmp(31); const uid3 = empLive.body?.employee?.userId; if (uid3) fx.created.users.push(uid3);
  await openPortal(page, cfg, "admin", "/employees");
  const endedText = await page.getByTestId(`emp:${uid}`).innerText().catch(() => ""); const liveText = await page.getByTestId(`emp:${uid3}`).innerText().catch(() => "");
  const endedMs = (await get(sa, `/employees/${uid}/organization-memberships`)).body ?? []; const endedPos = (await get(sa, `/employees/${uid}/positions`)).body ?? [];
  check.ok("25d UI lifecycle: the employee whose Flutter membership and position were ENDED (case 14) shows only the remaining unit and no position in the active directory; an employee created now and never ended shows unit path, position and grade; both read 'Chờ kích hoạt'", /Mobile/.test(endedText) && !/Flutter/.test(endedText) && !/Kỹ sư/.test(endedText) && !/Senior/.test(endedText) && /Chưa gán/.test(endedText) && /Chờ kích hoạt/.test(endedText) && endedMs.length === 1 && endedPos.length === 0 && /Flutter/.test(liveText) && /Kỹ sư/.test(liveText) && /Senior/.test(liveText) && /Chờ kích hoạt/.test(liveText), `REQUEST open /admin/employees · EXPECTED ended: Mobile only, no position (server: 1 membership, 0 positions) · live: Flutter / Kỹ sư / Senior · ACTUAL ended=${endedText.replace(/\s+/g, " ").slice(0, 110)} (server ${endedMs.length} memberships, ${endedPos.length} positions) · live=${liveText.replace(/\s+/g, " ").slice(0, 110)} · UI rows · SERVER u=${uid}, u2=${uid3}`, "ui");
  check.ok("25e no API 4xx/5xx that the screens caused by themselves and no console error during the UI steps (the only thing set aside: the login page's own pre-session GET /auth/me → 401)", preAuthUnexpected.length === 0 && badApi.length === 0 && pageProblems(page).length === 0, `pre-session probes: ${preAuth.join(" | ") || "none"} · after login: ${badApi.join(" | ") || "none"} ${pageProblems(page).slice(0, 2).join(" | ")}`, "ui");
  await page.context().close();
}
