#!/usr/bin/env python3
"""Builds docs/parallel/c6/USER_GUIDE_QA.md (+ .tsv) for docs/user-guide/C5_STUDIO_USER_GUIDE.md @ db4d595.
Raw observations: evidence/user-guide-20261007/ug-run.json (first pass) and probe2..5.json (re-probes of steps whose first result was a harness error).
A step whose first-pass status was wrong is NOT edited in ug-run.json; the corrected verdict is set here with the reason in the 'Actual result' column."""
import json, os, re
D = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(D); EV = ROOT + "/evidence/user-guide-20261007/"
R = json.load(open(EV + "ug-run.json"))["R"]
def run(i, k="ui", n=230):
    v = (R.get(i) or {}).get(k) or "-"; return re.sub(r"\s+", " ", v)[:n]
ADM = "WORKSPACE_ADMIN + project OWNER (demo01)"
S = []  # id, section, guide, label, role, eui, aui, eapi, aapi, eres, ares, status, finding, owner, evidence
def add(*a): S.append(a)
RUN = "RUN"
E = lambda *x: "; ".join(x)
# ---- §0
add("UG-001","§0","Open https://studio.toolsmcp.uk/studio","none","anonymous","login page",RUN,"GET /api/v1/auth/me 401","GET /api/v1/auth/me 401; auth/config 200","Studio opens","Redirect to /login?next=/studio, title 'AI Software Factory'","PASS","HTTP 200 alone does not prove the version (UG-008)","-","ug-run.json UG-001, probe.json")
add("UG-002","§0","Admin console …/admin","none","anonymous","admin entry",RUN,"-","auth/me 401","Admin reachable","Same login page (no separate admin login)","PASS","-","-","ug-run.json UG-002")
add("UG-003","§0","Platform …/platform","none","anonymous","platform entry",RUN,"-","auth/me 401","Platform reachable","Same login page","PASS","-","-","ug-run.json UG-003")
add("UG-004","§0","API has no separate host; browser calls /api/v1 on the Studio origin","none","anonymous","-",RUN,"same-origin /api/v1",RUN.replace(RUN,"") or "auth/config 200 same origin; separate host does not answer","same-origin proxy","Confirmed","PASS","-","-","ug-run.json UG-004")
add("UG-005","§0","Published sites https://sites.toolsmcp.uk/<slug>/","none","anonymous","-",RUN,"GET sites/healthz",RUN,"sites host answers","healthz 200; real slug exercised in UG-026","PASS","-","-","ug-run.json UG-005, UG-026")
add("UG-006","§0 Accounts","Accounts local.admin | local.editor | local.publisher | local.viewer exist (local profile seeds them)","none","all four","4 working logins on the public URL","public DB: users=14, local.* prefixed=0; workspace role WORKSPACE_ADMIN=14; project role OWNER=27","POST /api/v1/auth/login 200 for each","not attempted (accounts absent; read-only DB count, no names/hashes printed)","Four role accounts usable","They do NOT exist on the public instance; the sentence says 'local profile' but sits in the section that lists the public URLs and §10 tells the demo to 'log in as the editor account'","FAIL","WRONG GUIDE: reader cannot use these accounts on the public Studio; no EDITOR/PUBLISHER/VIEWER account exists to test roles. Guide must say accounts exist only on a local stack and how a public tester gets one","C5/C7 (guide); C0 (accounts for public QA)","version-check.txt")
add("UG-007","§0 Accounts","'On the public instance anyone can sign up (limit 5 per IP per hour)'","none","anonymous","sign-up link on /login","/login shows only 'Đăng nhập' (no sign-up)","auth/config signup=true","GET /api/v1/auth/config -> signup=false, signupInviteRequired=false","Self-service sign-up","Sign-up is disabled","FAIL","WRONG GUIDE: false statement (also repeated in §7.8 'Sign-up limit 5 per IP per hour')","C5/C7 (text); C0 if sign-up is meant to be on","probe.json, version-check.txt")
add("UG-008","§0 / version","Studio row: 'whether it already runs the V1 build is C0's to confirm'","none","-","public build = integration/v2 @ 1a9995c","no SHA/version shown in the UI","an endpoint that returns the build SHA","none: /actuator/* is answered by the Next app (HTML); /api/v1/version needs login (401). Jar built 14:44 and started 14:48 on 2026-10-07; backend sources last changed 13:29 (26cd3ab); .next built 2026-10-06 14:46, frontend sources last changed 14:42; 1a9995c (15:07) touched only compose/infra/scripts/docs; Flyway on the public DB = 30","Public build provably runs INTEGRATION_SHA","Circumstantially consistent (artifacts newer than the last code change) but NOT provable: no SHA embedded or exposed","BLOCKED","ENVIRONMENT/DEPLOYMENT: PUBLIC VERSION VERIFIED = NO. All results below are for 'the public build as deployed', not proven for 1a9995c. Fix: C0 embeds the git SHA in the jar (build-info) and the Next build and exposes it","C0","version-check.txt")
add("UG-009","§0","Local (developer) Studio http://127.0.0.1:3003/studio","none","-","-","only 'HTTP 200' observed; the user's local stack was not exercised","-","GET 127.0.0.1:3003/studio 200","Local Studio opens","Not tested: this QA targets the public Studio and the user's local stack is not touched","BLOCKED","not in scope of this run","-","this file")
# ---- §1
add("UG-010","§1.1","Open the Studio address; log in with Tên đăng nhập / Mật khẩu → Đăng nhập","REAL E2E-01","any (demo01)","labels 'Tên đăng nhập','Mật khẩu', button 'Đăng nhập'",RUN,"POST /auth/login 200 → /studio",RUN,"Logged in, Studio home","Logged in; but the page first asks 'Bạn muốn vào' (radio Admin Console / Builder Studio, Builder Studio preselected)","PASS","MISSING STEP (minor): the portal chooser is not mentioned; default is correct so no guess was needed","C5/C7","ug-run.json UG-010, probe_login.png")
add("UG-011","§1.1","A wrong password shows 'Sai tên đăng nhập hoặc mật khẩu.'","REAL E2E-01","anonymous","exact message",RUN,"POST /auth/login 401",RUN,"Message shown","Exact text shown","PASS","-","-","ug-run.json UG-011")
add("UG-012","§1.2","Sidebar Ứng dụng","REAL E2E-02","demo01","link 'Ứng dụng'",RUN,"-","-","Opens project list","/studio/projects","PASS","-","-","ug-run.json UG-012")
add("UG-013","§1.2","+ Tạo ứng dụng","REAL","demo01","link '+ Tạo ứng dụng'",RUN,"GET /templates",RUN,"Opens the create page","/studio/new","PASS","-","-","ug-run.json UG-013")
add("UG-014","§1.2","Choose Website (card shows 'Sẵn sàng')","REAL","demo01","card 'Website' + 'Sẵn sàng'",RUN,"-","-","Card present","Present","PASS","-","-","ug-run.json UG-014, ug-create.png")
add("UG-015","§1.2","Keep Trang mặc định under 'Bắt đầu từ'","REAL","demo01","radio 'Trang mặc định' default",RUN,"-","-","Preselected","Preselected","PASS","-","-","ug-run.json UG-015")
add("UG-016","§1.2","Type Tên ứng dụng","REAL","demo01","field 'Tên ứng dụng'",RUN,"-","-","Field exists","Placeholder 'Tên ứng dụng', no visible label","PASS","-","-","ug-run.json UG-016")
add("UG-017","§1.2","Tạo website","REAL","demo01","button 'Tạo website'",RUN,"POST /workspaces/{id}/projects 201",RUN,"Project created, editor opens","Created (201); editor at /studio/projects/{id}/ai","PASS","(see UG-019 for the mode)","-","ug-run.json UG-017")
add("UG-018","§1.2","Other kinds say 'Chưa bật' with the reason","REAL","demo01","5 other cards 'Chưa bật'",RUN,"auth/config codeProjects/serverApps=false",RUN,"Disabled with reasons","All five show 'Chưa bật' + reason","PASS","-","-","ug-run.json UG-018")
add("UG-019","§1.3","The editor opens in Design","REAL E2E-02","demo01","URL …/design, Design tab active",RUN,"-","-","Design mode on open","Opens in ✦ AI mode (/ai); Design is one click away","FAIL","WRONG GUIDE (order): every later step assumes Design; a first-time user lands on the AI chat. Either text or default mode is wrong","C5/C7 (text) — C5 decides whether AI-first is intended","ug-run.json UG-019, ug-after-create.png")
add("UG-020","§1.3","Click a section in the canvas, edit its text in the right panel","REAL E2E-02","demo01","right panel 'Nội dung' → field 'Tiêu đề'",RUN,"PATCH …/schema 200",RUN,"Edit accepted","Edited; an explicit button 'Lưu thay đổi' must be pressed","PASS","MISSING STEP: guide never mentions 'Lưu thay đổi' / 'Hoàn tác'; it reads as auto-save","C5/C7","ug-run.json UG-020")
add("UG-021","§1.3","Top bar shows Đang lưu… then ✓ Đã lưu hh:mm","REAL E2E-02","demo01","'Đang lưu…' → '✓ Đã lưu hh:mm'",RUN,"PATCH …/schema 200",RUN,"Both states seen","Seen after pressing 'Lưu thay đổi'","PASS","-","-","ug-run.json UG-021, ug-after-edit.png")
add("UG-022","§1.3","Reload: the edit is still there","REAL E2E-02","demo01","edited title present",RUN,"GET …/schema, …/versions",RUN,"Persisted","Persisted","PASS","-","-","ug-run.json UG-022")
add("UG-023","§1.4","Click Xuất bản (top right) → dialog 'Xuất bản website'; options Riêng tư / Công khai","REAL P01","demo01","dialog title + both options",RUN,"GET …/site, …/deployments",RUN,"Dialog with both options","As described","PASS","-","-","ug-run.json UG-023")
add("UG-024","§1.4","Choose Công khai → Xuất bản; statuses shown live until RUNNING","REAL P01","demo01 (owner)","statuses",RUN,"POST …/publish 202; GET …/deployments",RUN,"RUNNING","RUNNING","PASS","-","-","ug-run.json UG-024")
add("UG-025","§1.4","At RUNNING the dialog shows 'Website đã lên: <link>'","REAL P01","demo01","'Website đã lên: <link>'",RUN,"-","-","Link shown","'Website đã lên: https://sites.toolsmcp.uk/<slug>/' shown","PASS","-","-","ug-run.json UG-025, ug-published-1.png")
add("UG-026","§1.4","Open the link: your page, served from …/<slug>/","REAL P01","anonymous","public page with the edit",RUN,"GET sites/<slug>/ (no cookie)",RUN,"Anonymous 200 with the edited title","200 with the edited title","PASS","-","-","ug-run.json UG-026")
# ---- §2.1
add("UG-030","§2.1","Mode tabs: Design, ✦ AI, Code","UI","demo01","3 tabs",RUN,"-","-","Present","Present","PASS","-","-","ug-run.json UG-030")
add("UG-031","§2.1","Code (website shows an explanation)","UI","demo01","explanation text",RUN,"-","-","Explanation","'Chưa triển khai…' explanation","PASS","-","-","ug-run.json UG-031")
add("UG-032","§2.1","Design top bar: Chỉnh sửa | Dùng thử, screen sizes, Chia sẻ, Xuất bản","UI","demo01","all items",RUN,"-","-","Present","Present (the red/amber problem counter was not triggered)","PASS","-","-","ug-run.json UG-032")
add("UG-033","§2.1","Older header (AI/Code modes): Website · Phiên bản · Tệp · Chia sẻ · ⚙ · Xuất bản","UI","demo01","6 items",RUN,"-","-","Present","Present","PASS","-","-","ug-run.json UG-033")
# ---- §2.2
add("UG-040","§2.2","Left rail 'Công cụ': Trang · Thành phần · Dữ liệu · Biểu mẫu · Hành động · Workflow · Giao diện · AI","REAL E2E-02","demo01","rail named 'Công cụ' with 8 items",RUN,"-","-","8 items under 'Công cụ'","8 items exactly as listed; 'Công cụ' exists only as the accessible name (aria-label), no visible heading (probe5.json: aria-label='Công cụ' count 1)","PASS","Minor: first-pass FAIL was a harness check of visible text; re-probed. A sighted user sees no 'Công cụ' heading","C5/C7 (minor)","ug-run.json UG-040, probe5.json")
add("UG-041","§2.2","Select a section → inspector tabs Nội dung · Thiết kế · Dữ liệu · Hành động · Quyền · Nâng cao","UI","demo01","6 tabs",RUN,"-","-","6 tabs","6 tabs ('Thiết kế' carries an extra 'chưa' badge)","PASS","-","-","ug-run.json UG-041")
add("UG-042","§2.2","Every change is saved as an immutable version on the server","REAL","demo01","Phiên bản N · revision M",RUN,"GET …/versions",RUN,"New version per save","Versions grow with each save","PASS","-","-","ug-run.json UG-042, ug-versions.png")
add("UG-043","§2.2","Offline / server down: 'Lưu thất bại' + 'Thử lại'; retry sends the same edit once","REAL S2,S6,S9","demo01","'Lưu thất bại' and a 'Thử lại' button",RUN,"retry = 1 PATCH 200",RUN,"Failure + retry control","Top bar shows 'Lưu thất bại' and a toast 'Không kết nối được tới máy chủ. Kiểm tra backend rồi thử lại.'; there is NO 'Thử lại' button; pressing 'Lưu thay đổi' again online saves (PATCH 200)","FAIL","[REAL] claim not reproducible. Code: the retry button is in BuilderTopBar on agent/c5-web @ db4d595 only; integration/v2 does not contain it (see F-02). The toast also tells the user to 'check backend'","C5 (merge the retry) + C0 (integrate); C5/C7 (guide must match the build)","ug-run.json UG-043, explore-offline.png")
add("UG-044","§2.2","Someone else saved first: page reloads the newer version, asks to repeat the edit (409)","REAL S5","demo01 ×2 sessions","message 'Project vừa được thay đổi ở nơi khác…'",RUN,"PATCH …/schema 409",RUN,"409 handled","409 + message shown","PASS","-","-","ug-run.json UG-044")
add("UG-045","§2.2","Double click never runs an action twice","REAL S4","demo01","-","no action can be authored on the public Studio (UG-091)","-","-","No double execution","Not testable","BLOCKED","Depends on actions (F-12)","C4 / C0","probe2.json")
# ---- §2.3
add("UG-050","§2.3","Phiên bản → Lịch sử phiên bản","UI","demo01","drawer 'Lịch sử phiên bản' + 'Khôi phục' buttons",RUN,"GET …/versions",RUN,"History drawer","Drawer with 5 versions","PASS","-","-","ug-run.json UG-050, ug-versions.png")
add("UG-051","§2.3","Khôi phục creates a NEW version; old versions never change","UI","demo01","'Khôi phục'","click raises a native browser confirm 'Khôi phục phiên bản N? Một phiên bản mới sẽ được tạo; lịch sử cũ giữ nguyên.' (accepted)","POST …/versions/{id}/restore","POST …/versions/{id}/restore 200; versions 5 → 7 after two restores, none removed (probe2.json)","New version, old kept","Confirmed","PASS","MISSING STEP (minor): the native confirm is not mentioned. First-pass FAIL was the harness auto-dismissing it","C5/C7","probe2.json, ug-restore-click.png")
# ---- §2.4
add("UG-060","§2.4","Mode ✦ AI: describe the change in 'Mô tả thay đổi', 'Gửi ↑'","UI","demo01","field 'Mô tả thay đổi', button 'Gửi ↑'","field present (aria-label 'Mô tả thay đổi', placeholder 'Mô tả thay đổi bạn muốn tạo…'); button 'Gửi ↑'","POST …/prompts","POST …/prompts 200","Labels exist","Labels exist (first-pass FAIL looked for visible text only)","PASS","-","-","probe2.json aiPlaceholders, ug-ai-screen.png")
add("UG-061","§2.4","While it runs: steps, elapsed time, countdown to automatic stop (120 s), Huỷ","UI","demo01","progress panel","simulator answered at once: 'Mock LLM chưa hiểu yêu cầu này; nội dung không thay đổi. UNSUPPORTED'; no progress panel observed","-","POST …/prompts 200","Progress visible","Not observable with the simulator. Code check: the progress panel is commit 7892bda, which is NOT in integration/v2","BLOCKED","[UI] claim cannot be shown on this build; F-02","C5 (merge) / C0","ug-run.json UG-061, ug-ai-screen.png")
add("UG-062","§2.4","After 15 s of silence it says so and suggests cancelling / another model","UI","demo01","message","needs a real model to stay silent; no data is sent to external AI providers by C6","-","-","Message","Not executed","BLOCKED","-","C5","-")
add("UG-063","§2.4","Otherwise the app runs in 'Chế độ thử nghiệm' (simulator, no data leaves)","UI","demo01","model option",RUN,"-","-","Simulator selectable","Option 'Chế độ thử nghiệm (không dùng AI thật)' exists; default 'Tự động' routes to OpenRouter free models (a provider is already configured on the public instance, so the guide's 'otherwise' does not describe the default)","PASS","Minor: default is NOT the simulator on this instance","C5/C7 (minor)","ug-run.json UG-063")
add("UG-064","§2.4","Admin → AI → + Thêm nhà cung cấp (admin adds a provider and key)","UI","system admin","Admin console AI page","demo01 + 'Admin Console' radio → /auth/no-access ('Bạn không có quyền truy cập Admin Console')","-","POST /auth/login 200 then redirect","Admin AI page","Needs a system administrator; the operator account was not used","BLOCKED","gate behaves correctly for a non-system-admin","-","ug-run.json UG-064")
# ---- §3
roles = [("UG-070","Open an app needs APP_VIEW, otherwise 'no access' page","VIEWER without access"),("UG-071","Edit needs APP_EDIT; without it the app is read-only with a notice","VIEWER"),("UG-072","Share needs APP_SHARE: 'Chia sẻ' disabled with the reason","EDITOR/VIEWER"),("UG-073","Publish / rollback / unpublish need APP_PUBLISH: 'Xuất bản' and history actions disabled with the reason","EDITOR (negative), PUBLISHER (positive)"),("UG-074","Test needs APP_USE + execute right (+APP_EDIT): 'Chạy thử' disabled and names what is missing","VIEWER/EDITOR"),("UG-075","Data sources need DATA_SOURCE_MANAGE (view DATA_SOURCE_VIEW): panel read-only without it","EDITOR")]
for i, t, r in roles:
    add(i,"§3",t,"partly REAL",r,"as described","not executed: the public instance has no EDITOR/PUBLISHER/VIEWER account (all 14 are WORKSPACE_ADMIN, all 27 project memberships OWNER); sign-up is off; creating users needs a system admin","403/404 on the forbidden call","-","Role-specific UI effect","Cannot be tested on the public Studio","BLOCKED","ENVIRONMENT: no role accounts (see UG-006). Not an app verdict. API-level role matrix for a local stack was covered earlier by C6RuntimePermissionHttpTests, not for this guide","C0 (provide role accounts) / C5/C7","version-check.txt")
add("UG-076","§3","Project roles: VIEWER = view+use · EDITOR = + edit, data view, execute · PUBLISHER = + publish","partly REAL","EDITOR, PUBLISHER, VIEWER","role capabilities","not executed (no accounts)","403 outside the role","-","Matches table","Cannot be tested on the public Studio","BLOCKED","ENVIRONMENT (UG-006). Owner role (demo01) edited and published successfully: positive path only","C0","-")
add("UG-077","§3","Limitation H-C1-04: a VIEWER-only account is refused at the portal gate","limitation","VIEWER","guide states the limitation","guide states it in §3, §7.3 and §8; not reproducible without a viewer account","GET /auth/me has no project permissions","-","Limitation stated, not claimed as working","Stated correctly","PASS","-","C1 (product)","guide §3/§7/§8")
# ---- §4
add("UG-080","§4","Rail Dữ liệu steps: Nguồn dữ liệu · Khám phá cấu trúc · Truy vấn · Ánh xạ · ViewModel · Gắn vào thành phần · Dữ liệu công khai","UI/REAL","demo01","7 steps",RUN,"-","-","7 steps","6 steps: …Gắn vào thành phần; 'Dữ liệu công khai' is not a step, and the panel shows 'Chưa sẵn sàng — Chưa có API liệt kê nguồn dữ liệu (Data Platform của C3 chưa nối vào máy chủ)'","FAIL","Guide describes agent/c5-web, not the integrated build (F-02, F-12)","C0 (merge C5 UI) / C5 / C5/C7 (guide)","ug-run.json UG-080, ug-data-rail.png, probe5.json")
add("UG-081","§4","Data sources: 'Thêm nguồn dữ liệu' (type, config, credential)","REAL E2E-06 (23 API + 9 UI)","admin","button 'Thêm nguồn dữ liệu'","button absent; panel says the Data Platform is not wired to the server","POST /workspaces/{id}/data-sources","GET /workspaces/{id}/data-sources -> 200 {items:[]} (the API exists on the public backend; C6 did not POST: a source needs a public DNS DB host, guide §7.1)","Create a source from the Studio","The Studio has no control to create one","FAIL","[REAL] claim NOT reproducible from the UI of the public/integrated build (mandatory finding). The backend route answers, so the gap is the UI: C5's panel is not in integration/v2. (§7.1 also says no source can be created on a local stack, next to 'REAL for sources')","C0 (merge C5 UI) + C5; C5/C7 (claim vs build)","ug-data-rail.png, probe5.json, probe6.json")
add("UG-082","§4","'Kiểm tra kết nối'","REAL E2E-06","admin","button","needs an existing source","POST …/test","-","Test result","Not executable (UG-081)","BLOCKED","depends on UG-081","C3","-")
add("UG-083","§4","Credential is write-only: never shown again, only key names","REAL E2E-06","admin","masked","needs an existing source","GET shows no secret","-","No secret in responses","Not executable","BLOCKED","depends on UG-081","C3","-")
add("UG-084","§4","Slots ('Khe dữ liệu'): 'Thêm khe' (id lowercase, type such as postgres)","REAL PD02","editor/admin","'Khe dữ liệu', 'Thêm khe'","neither label appears anywhere in the Data rail or the inspector (probe5.json)","slot operations (B-C0-W-07)","-","Slot created","Absent","FAIL","[REAL] claim not reproducible; labels exist only in features/studio/builder/DataSourcesPanel.tsx on agent/c5-web @ db4d595 (not in integration/v2)","C5 (merge) + C0; C2 (slot ops)","probe5.json")
add("UG-085","§4","Administrator binds a slot: 'Liên kết khe dữ liệu' (TEST / LIVE)","REAL PD02","admin","label","absent","bind slot","-","Binding","Absent","BLOCKED","depends on UG-084","C5/C0","probe5.json")
add("UG-086","§4","Queries, mappings, ViewModels, bindings editors exist","UI","demo01","steps present","step labels Truy vấn / Ánh xạ / ViewModel / Gắn vào thành phần present; content not exercised (no source)","-","-","Editors usable","Labels only","BLOCKED","needs a source (UG-081)","C3","ug-data-rail.png")
add("UG-087","§4","Public data: tab 'Dữ liệu công khai'","REAL PD02","editor/admin","tab",RUN,"-","-","Tab present","Absent","FAIL","as UG-084 (PublicDataPanels.tsx exists only on agent/c5-web)","C5 (merge) + C0","probe5.json")
add("UG-088","§4","A READ query can be switched Công khai; a WRITE query cannot; bind a prop to a public query","REAL PD02","editor","switch","not executable (no query)","-","-","as described","Not executable","BLOCKED","depends on UG-081/087","C3/C2","-")
add("UG-089","§4","Publishing lists what becomes public and asks you to tick the confirmation","REAL PD02","admin","confirmation in dialog","not triggered (no public query; the publish dialog of this build shows no such tick)","-","-","Confirmation","Not reproducible","BLOCKED","depends on UG-088; H-C2-07 enforcement is a separate server-side limitation (UG-124)","C2","ug-published-1.png")
# ---- §5
add("UG-090","§5","Mode Dùng thử: banner 'Chế độ dùng thử — không lưu thay đổi vào dữ liệu thật'","REAL","demo01","exact banner",RUN,"-","-","Exact banner","Title 'Chế độ dùng thử' + sentence 'Không lưu thay đổi vào dữ liệu thật. Muốn sửa ứng dụng, chuyển về “Chỉnh sửa”.' plus a notice 'Chưa có API Test Mode. “Dùng thử” sẽ chạy thật qua máy chủ, không giả lập thành công ở trình duyệt.'","FAIL","WRONG LABEL (minor): the quoted banner does not exist verbatim; and the panel itself says there is no Test Mode API yet","C5/C7 (text); C4 (Test Mode API)","ug-run.json UG-090, ug-test-mode.png")
add("UG-091","§5","Rail Hành động / Workflow: '+ Thêm hành động', 'Thêm workflow'","REAL","demo01","buttons","buttons absent; Hành động panel: 'Chưa sẵn sàng — Chưa có adapter chạy hành động (ActionDataPort của C4 chưa được nối vào máy chủ)'; Workflow panel: 'Chưa có API khởi chạy và theo dõi workflow (WorkflowRuntime của C4 chưa nối vào máy chủ)'","POST …/app-runtime/actions/{id}/execute, POST …/app-runtime/workflows/{id}/runs","routes resolve to their controller on the public backend (…/app-runtime/workflow-runs/{id} -> PROJECT_NOT_FOUND, a bogus sub-path -> NOT_FOUND); no action could be authored from the UI (probe6.json)","Author an action / workflow from the Studio","Impossible from the UI of this build","FAIL","[REAL] claim (E2E-S1/S8/11/12) not reproducible from the UI. Backend routes exist; the Studio panels say ActionDataPort / WorkflowRuntime are not wired to the server. The guide also never says how to author one (MISSING STEP)","C0 (merge C5 UI) + C5; C4 only for the runtime itself; C5/C7","probe2.json, ug-rail-Hành động.png, ug-rail-Workflow.png")
add("UG-092","§5","Chạy thử: a TEST action reports 'would run', sends nothing","REAL S1","demo01","'Chạy thử'","no action to run (UG-091); Test panel: 'Hành động (0) Chưa có hành động nào để thử'","-","-","'would run'","Not executable","BLOCKED","depends on UG-091","C4","ug-test-mode.png")
add("UG-093","§5","A workflow start creates a run and shows its steps; a failed run is shown failed","REAL 11, S8","demo01","run steps","no workflow can be created","-","-","Run shown","Not executable","BLOCKED","depends on UG-091","C4","ug-test-mode.png")
add("UG-094","§5","Step kinds ACTION, WAIT, APPROVAL, BRANCH, END","UI","demo01","kinds listed","Workflow panel text lists wait, approval, branch, end","-","-","Kinds present","Listed; not authorable","BLOCKED","depends on UG-091","C4","probe2.json")
add("UG-095","§5","A workflow run in Test mode can still create a run record","REAL","demo01","note","note shown verbatim in the Test panel","-","-","Stated","Stated; behaviour not exercised","BLOCKED","depends on UG-091","C4","ug-test-mode.png")
add("UG-096","§5","Runs survive a backend restart (E2E-12, durable run store)","REAL 12","operator","-","not executed: the public stack is not restarted by QA","-","-","Runs persist","Not executed","BLOCKED","would interrupt the user's public stack","C4/C0","-")
# ---- §6
add("UG-100","§6","FAILED shows the server's reason","REAL P","demo01","reason in dialog","not triggered (no failing publish was produced)","-","-","Reason shown","Not executed","BLOCKED","-","C2","-")
add("UG-101","§6","Riêng tư (members only, sign in with a company account)","REAL P","owner + 2nd member","private page","not executed (needs a second member account)","-","-","Anonymous refused, member allowed","Not executed","BLOCKED","ENVIRONMENT: no second account","C2/C0","-")
add("UG-102","§6","The history 'Các lần xuất bản (N)' lists RUNNING releases","REAL P","demo01","list of RUNNING only","after rollback the list shows 1 entry ('Phiên bản 2 · công khai · hh:mm'); ROLLED_BACK releases are not listed","GET …/deployments","GET …/deployments 200","RUNNING only","As described","PASS","-","-","probe3.json")
add("UG-103","§6","Open the history 'Các lần xuất bản (N)'","REAL P","demo01","list with 'Phục vụ lại bản này'",RUN,"GET …/deployments",RUN,"Entries visible","Entries are hidden until the heading 'Các lần xuất bản (N)' is clicked","PASS","MISSING STEP: the guide never says the history is collapsed and must be expanded (the guide's button 'Phục vụ lại bản này' is not visible otherwise)","C5/C7","ug-run.json UG-103, ug-history.png")
add("UG-104","§6","'Phục vụ lại bản này' re-serves an older release","REAL P","demo01 (owner)","button",RUN,"POST …/site/rollback 200",RUN,"Old content served","Public page showed the old content","PASS","-","-","ug-run.json UG-104")
add("UG-105","§6","The release you left becomes ROLLED_BACK and cannot be served again","REAL P","demo01","status",RUN,"GET …/deployments",RUN,"ROLLED_BACK","ROLLED_BACK; the UI offers no 'Phục vụ lại' for it","PASS","-","-","ug-run.json UG-105")
add("UG-106","§6","'Gỡ trang xuống' takes the site offline (history kept; a rollback brings it back)","REAL P","demo01 (owner)","button 'Gỡ trang xuống'","click raises a native confirm 'Gỡ trang xuống? Địa chỉ sẽ báo không tìm thấy cho tới khi xuất bản lại hoặc phục vụ lại một bản cũ.' (accepted); then history kept: 'Các lần xuất bản (1)'; 'Phục vụ lại bản này' brings it back","DELETE …/site","DELETE …/site 200 → public GET 404; POST …/site/rollback 200 → public GET 200 (probe2.json, probe3.json)","Offline, then back","Confirmed","PASS","MISSING STEP (minor): native confirm not mentioned. First-pass FAIL was the harness auto-dismissing it","C5/C7","probe2.json, probe3.json, ug-unpublish-click.png")
add("UG-107","§6","Another publish/rollback in progress: banner 'đang xuất bản/đang hoàn tác', buttons locked; a conflicting request answers 'bận' with a countdown","REAL P","demo01","banner + countdown","not observed: a rollback fired in parallel with a publish returned 200 (the publish had not taken the scope yet); no UI banner captured. The banner text 'đang xuất bản' is not in integration/v2 code","409 SCOPE_BUSY + Retry-After","200, no Retry-After (probe4.json)","409 busy","Contention not reproduced","BLOCKED","Not a verdict on the product: C6 could not make the window deterministic. UI banner not found in integration/v2 code (F-02)","C2 (lease) / C5 (banner)","probe4.json")
add("UG-108","§6","If the active release changed under you, rollback says it is stale","REAL P","demo01","stale message","API only (UI text not triggered)","POST …/site/rollback expectedActiveDeploymentId=<wrong>","409 ROLLBACK_STALE, active release unchanged (probe4.json, with a non-active target)","409 stale","Confirmed","PASS","First-pass FAIL was a harness error (the target was the active release, which skips the stale check by design). The Studio UI does not send expectedActiveDeploymentId","C2 (API ok); C5 (UI does not use it)","probe4.json")
add("UG-109","§6","A publish overtaken by a newer release ends FAILED 'Bản xuất bản này đã cũ hơn bản đang chạy'","REAL P","demo01","message","not triggered (needs two publishes racing)","FAILED / STALE_PUBLISH","-","FAILED with that text","Not executed","BLOCKED","needs a deterministic race","C2","-")
add("UG-110","§6","A repeated click never creates a second operation (idempotency key per request)","REAL P","demo01","-","API only","2 × POST …/publish with one Idempotency-Key","202 / 202 with the same deployment id","one operation","Confirmed","PASS","-","-","ug-run.json UG-110")
# ---- §7/§8 limitations: guide statements vs evidence
lim = [("UG-120","§7.1/§8","Query on real data, mutation with a real side effect, TEST/LIVE binding results are NOT verified","real query / real mutation","Guide lists them as BLOCKED; C6 found nothing contradicting (no source can be created, UG-081)","PASS","guide states it as a limitation; but §4 header still says '[REAL for sources]' (UG-081 contradiction)"),
 ("UG-121","§7.2/§8","Published real data (PD01 rendered rows) NOT demonstrated","published real data","Guide lists PD01 as BLOCKED; the published page showed authored text only (UG-026)","PASS","consistent"),
 ("UG-122","§7.3/§8","VIEWER read-only (H-C1-04)","viewer","Stated in §3, §7 and §8","PASS","consistent"),
 ("UG-123","§7.4","RabbitMQ outage recovery (E2E-14) and notification actions BLOCKED/PARTIAL","E2E-14 / NOTIFY","Stated; not exercised by C6 (no stack restart)","PASS","consistent"),
 ("UG-124","§7.5/§8","Public-data acknowledgement is only a local confirmation; server does not enforce it (H-C2-07)","H-C2-07","Stated; guide also says (UG-089) that publishing 'asks you to tick the confirmation' — that dialog element was not present on this build","PASS","statement matches the limitation; the dialog claim is UG-089"),
 ("UG-125","§2.4/§8","AI end to end not verified; 'AI always answers / is fast' not to be claimed","AI real E2E","Stated; C6 used only the simulator","PASS","consistent"),
 ("UG-126","§7.6","Studio preview shows authored text, never live data","-","Preview and the published page show authored text","PASS","observed"),
 ("UG-127","§7.7","Code apps / server apps are 'Chưa bật' on the public instance","-","UG-018: codeProjects=false, serverApps=false","PASS","observed"),
 ("UG-128","§7.8","Sign-up limit 5 per IP per hour","-","sign-up is disabled (UG-007)","FAIL","same false statement as UG-007")]
for i, sec, t, lab, act, st, fnd in lim:
    add(i, sec, t, "limitation", "-", "stated, not presented as verified", act, "-", "-", "Honest limitation", fnd, st, ("WRONG GUIDE: " + fnd) if st == "FAIL" else "-", "C5/C7" if st == "FAIL" else "-", "guide text")
# ---- §10 demo script
add("UG-130","§10.1","(1 min) Log in as the editor account; show Ứng dụng","REAL","EDITOR","editor login","no editor account on the public Studio; demo01 is a workspace admin","-","-","Editor can log in","Cannot be done as written","FAIL","WRONG GUIDE / ENVIRONMENT (UG-006)","C5/C7; C0","version-check.txt")
add("UG-131","§10.2","(2 min) + Tạo ứng dụng → Website → Tạo website; the editor opens","REAL","any","-","as UG-013..017 (opens in AI mode)","-","-","-","Works","PASS","(UG-019 note)","-","ug-run.json")
add("UG-132","§10.3","(3 min) Change hero title; point at Đã lưu; reload; change stays; show Phiên bản history","REAL","any","-","as UG-020..022, UG-050 (requires 'Lưu thay đổi')","-","-","-","Works","PASS","(UG-020 missing step)","-","ug-run.json")
add("UG-133","§10.4","(2 min) Xuất bản → Công khai → Xuất bản; wait for RUNNING; open link in a private window","REAL","any","-","as UG-023..026","-","-","-","Works","PASS","-","-","ug-run.json")
add("UG-134","§10.5","(2 min) Edit, publish again, Xuất bản → Phục vụ lại bản này on the first release; old content back","REAL","any","-","as UG-103/104 (history must be expanded)","-","-","-","Works","PASS","(UG-103 missing step)","-","ug-run.json UG-104")
add("UG-135","§10.6","(1 min) Dùng thử; Chạy thử on a workflow/action prepared in advance; 'would run'","REAL","any","-","an action/workflow cannot be prepared on this build (UG-091)","-","-","'would run'","Demo step impossible","FAIL","DEMO BLOCKER: do not give this script to a user on the integrated build","C4/C0; C5/C7","probe2.json")
add("UG-136","§10.7","(1 min) Close with §7","-","any","-","§7 exists and is honest (UG-120..125)","-","-","-","Present","PASS","-","-","guide text")
# ---- §9 troubleshooting
add("UG-140","§9","'Lưu thất bại' + Thử lại","REAL","demo01","as UG-043","as UG-043","-","-","-","No 'Thử lại'","FAIL","as UG-043","C5/C0","ug-run.json UG-043")
add("UG-141","§9","'Project vừa được thay đổi ở nơi khác…'","REAL","demo01","message","shown (UG-044)","409","409","-","Matches","PASS","-","-","ug-run.json UG-044")
add("UG-142","§9","AI: 'Chưa có phản hồi nào từ model sau N giây'","UI","demo01","message","not reproduced (UG-062)","-","-","-","Not executed","BLOCKED","-","C5","-")
add("UG-143","§9","Xuất bản disabled: you lack APP_PUBLISH, or an operation is running; hover for the reason","REAL","EDITOR/VIEWER","disabled with reason","not executed (no role accounts)","-","-","-","Not executed","BLOCKED","ENVIRONMENT","C0","-")
add("UG-144","§9","'Công khai' not offered if the administrator disabled public publishing","UI","demo01","option hidden","publicPublish=true so the option is offered; the switch was not toggled by C6","-","auth/config publicPublish=true","-","Not executed","BLOCKED","would change the user's config","C0","probe.json")
add("UG-145","§9","Deployment FAILED: read the reason in the dialog","REAL","demo01","reason","no failing deployment produced","-","-","-","Not executed","BLOCKED","-","C2","-")
add("UG-146","§9","Page shows authored text, not data (expected today)","REAL","anonymous","authored text","published page shows authored text","-","200","-","Matches","PASS","-","-","ug-run.json UG-026")
add("UG-147","§9","530 / site not found: the public host is down","REAL","anonymous","-","unknown slug → 404 'not found' while the host is up","-","GET sites/<unknown>/ 404","-","Distinguishes 404 vs host down","PASS","(a deleted project's slug answered 403, not 404 — observation for C2, not a guide statement)","C2 (obs)","this run")
add("UG-148","§9","Admin dialogs unreadable: fixed in 808f98b; rebuild the Admin app","REAL","system admin","readable dialogs","not testable (needs a system admin); commit 808f98b is NOT in integration/v2","-","-","-","Not executed","BLOCKED","guide cites a commit that is not on the integration branch","C0/C5","git merge-base")
# ---------------------------------------------------------------- output
st = lambda s: sum(1 for x in S if x[11] == s)
H = ["Step ID","Section","Guide instruction","C5 CLAIM (label)","Role","Expected UI","Actual UI","Expected API","Actual API","Expected result","Actual result","C6 RESULT","Finding","Owner","Evidence"]
def cell(x, n=None):
    x = re.sub(r"\s+", " ", str(x)).replace("|", "¦"); return x if n is None or len(x) <= n else x[:n] + "…"
rows = []
for a in S:
    a = list(a); aui = a[6]; aapi = a[8]
    if aui == RUN: a[6] = run(a[0], "ui")
    if aapi == RUN or aapi == "": a[8] = run(a[0], "api")
    if a[7] == RUN: a[7] = "-"
    rows.append(a)
with open(ROOT + "/USER_GUIDE_QA.tsv", "w") as f:
    f.write("\t".join(H) + "\n")
    for a in rows: f.write("\t".join(re.sub(r"[\t\n]+", " ", str(c)) for c in a) + "\n")
real = [a for a in rows if str(a[3]).startswith("REAL") or "REAL" in str(a[3])]
rc = lambda s: sum(1 for a in real if a[11] == s)
tot = len(rows); P, F, B = st("PASS"), st("FAIL"), st("BLOCKED")
md = ["# USER GUIDE QA — `docs/user-guide/C5_STUDIO_USER_GUIDE.md`", "",
 "Generated by `harness/ug_matrix.py`. Raw evidence: `evidence/user-guide-20261007/` (`ug-run.json` first pass; `probe2..5.json` re-probes; `version-check.txt`). No token, cookie or password is recorded.", "",
 f"**Totals:** {tot} steps — PASS {P}, FAIL {F}, BLOCKED {B}.  **[REAL] claims:** {len(real)} — verified {rc('PASS')}, failed {rc('FAIL')}, blocked {rc('BLOCKED')}.", "",
 "| " + " | ".join(H) + " |", "|" + "---|" * len(H)]
for a in rows: md.append("| " + " | ".join(cell(c, 330) for c in a) + " |")
open(ROOT + "/USER_GUIDE_QA_MATRIX.md", "w").write("\n".join(md) + "\n")
print(tot, P, F, B, "REAL", len(real), rc("PASS"), rc("FAIL"), rc("BLOCKED"))
