import { useState } from "react";
import { Button, Card, Heading, Layout, Navbar, Stack, Text } from "@company/ui";
import { useRuntimeConfig } from "@company/app-sdk";

/** Starting point generated by the AI Software Factory. Edit with AI, in Design mode or in Code mode. */
export function App() {
  const [count, setCount] = useState(0);
  const config = useRuntimeConfig();
  return (
    <Layout header={<Navbar brand={config.appName} items={[{ label: "Trang chủ", href: "#", current: true }]}/>}>
      <Stack gap="lg" align="center">
        <Card padding="lg">
          <Text tone="muted">AI Software Factory</Text>
          <Heading level={1}>Ứng dụng mới của bạn</Heading>
          <Text>Mô tả thay đổi bằng AI hoặc sửa mã trong chế độ Code. Mỗi thay đổi được build trong sandbox trước khi xuất bản.</Text>
          <Button onClick={() => setCount((c) => c + 1)}>Đã bấm {count} lần</Button>
        </Card>
      </Stack>
    </Layout>
  );
}
