import { useState } from "react";

/** Starting point generated by the AI Software Factory. Edit with AI or in Code mode. */
export function App() {
  const [count, setCount] = useState(0);
  return (
    <main className="page">
      <section className="hero">
        <p className="eyebrow">AI Software Factory</p>
        <h1>Ứng dụng mới của bạn</h1>
        <p>Mô tả thay đổi bằng AI hoặc sửa mã trong chế độ Code. Mỗi thay đổi được build trong sandbox trước khi xuất bản.</p>
        <button type="button" onClick={() => setCount((c) => c + 1)}>Đã bấm {count} lần</button>
      </section>
    </main>
  );
}
