#!/usr/bin/env bash
# Run the whole app on this machine and publish it through a dedicated Cloudflare tunnel.
#   internet -> Cloudflare -> tunnel (hbl-studio) -> UI server 127.0.0.1:$UI_PORT  -> /api,/oauth2 -> API 127.0.0.1:$API_PORT
#                                                  -> storage host -> MinIO 127.0.0.1:$MINIO_PORT_PUBLIC (presigned URLs only)
#                                                  -> sites host -> sites gateway 127.0.0.1:$SITES_GATEWAY_PORT -> API /sites/** only
# Three public hostnames; the API, Postgres, Redis and RabbitMQ are never exposed. Secrets are generated once into
# .run/public/public.env (mode 600, git-ignored). Re-running is safe: it starts whatever is not running.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
RUN=.run/public; ENVF="$RUN/public.env"; mkdir -p "$RUN"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@21}"; [ -d /opt/homebrew/opt/openjdk@21 ] && export JAVA_HOME=/opt/homebrew/opt/openjdk@21; export PATH="$JAVA_HOME/bin:$PATH"
say() { printf '\n== %s\n' "$*"; }
gen() { openssl rand -base64 36 | tr -d '/+=\n' | cut -c1-32; }

if [ ! -f "$ENVF" ]; then
  say "generating $ENVF (new random secrets)"
  ( umask 077; cat > "$ENVF" <<ENV
# Generated by scripts/public-up.sh - contains secrets, never commit. Edit values freely, then re-run the script.
PUBLIC_HOST=${PUBLIC_HOST:-studio.toolsmcp.uk}
PUBLIC_FILES_HOST=${PUBLIC_FILES_HOST:-studio-files.toolsmcp.uk}
PUBLIC_ORIGIN=https://${PUBLIC_HOST:-studio.toolsmcp.uk}
API_PORT=18081
UI_PORT=3200
PG_PORT=25432
REDIS_PORT_PUBLIC=26379
MINIO_PORT_PUBLIC=29000
RABBITMQ_PORT_PUBLIC=25674
DATABASE_USER=studio
DATABASE_PASSWORD=$(gen)
REDIS_PASSWORD=$(gen)
RABBITMQ_PASSWORD=$(gen)
MINIO_ROOT_USER=studio$(gen | cut -c1-8)
MINIO_ROOT_PASSWORD=$(gen)
MINIO_BUCKET=studio-assets
# Operator account created on first start (system admin). Change or delete after first login if you like.
BOOTSTRAP_ADMIN_USERNAME=operator
BOOTSTRAP_ADMIN_PASSWORD=$(gen)
# Public sign-up is OFF for the internal pilot (accounts come from the operator or SSO). Set true only for a deliberate demo.
SIGNUP_ENABLED=false
SIGNUP_INVITE_CODE=
SIGNUP_MAX_USERS=500
SIGNUP_IP_MAX_PER_HOUR=5
MAX_PROJECTS_PER_WORKSPACE=20
MAX_ASSETS_PER_PROJECT=30
AI_DAILY_LIMIT_PER_USER=50
# AI: paste your OpenRouter key here (or run scripts/set-openrouter-key.sh). Empty = built-in simulator.
OPENROUTER_API_KEY=
ENV
  )
fi
# Real static sites (ADR 0009) — added to existing public.env files without touching other values
# Internal pilot policy (2026-10-03): no public sign-up, source apps for signed-in users only, code apps not published publicly by default
# website forms: a stable salt for hashing visitor IPs (stage G); server apps stay off on the pilot (no apps DB / runtime here)
# AI provider keys entered in the Admin Console are encrypted with this key (generated once, never printed; losing it makes saved keys unreadable)
grep -q '^SECRETS_MASTER_KEY=' "$ENVF" || ( umask 077; echo "SECRETS_MASTER_KEY=$(openssl rand -base64 32)" >> "$ENVF" )
grep -q '^FORMS_IP_SALT=' "$ENVF" || ( umask 077; echo "FORMS_IP_SALT=$(gen)" >> "$ENVF" )
grep -q '^SOURCE_APP_PUBLIC_PUBLISH_ENABLED=' "$ENVF" || ( umask 077; { echo "# Source-code apps (needs FORGEJO_* + runner); public publishing of code apps off for the pilot"; echo "SOURCE_APPS_ENABLED=true"; echo "SOURCE_APP_BUILD_ENABLED=true"; echo "SOURCE_APP_PUBLIC_PUBLISH_ENABLED=false"; } >> "$ENVF" )
grep -q '^SITES_HOST=' "$ENVF" || ( umask 077; { echo "# Published sites (gateway) — separate host from the Studio"; echo "SITES_HOST=sites.toolsmcp.uk"; echo "SITES_GATEWAY_PORT=28088"; echo "RENDER_PORT_PUBLIC=28095"; echo "RENDER_TOKEN=$(gen)"; } >> "$ENVF" )
set -a; . "$ENVF"; set +a
PUBLIC_ORIGIN="https://$PUBLIC_HOST"
# V1 feature set of the public environment (D-C0-38): data platform, workflow (RabbitMQ queue, the prod default), publish policy, the Public Runtime. All are OFF in the
# application unless stated here; V1_FEATURES=false brings the public stack back to its pre-V1 behaviour. apiBase is ONE value for every site ({slug} is replaced per site).
V1_FEATURES="${V1_FEATURES:-true}"
_slug='{slug}'; SITES_DATA_API_BASE="https://$SITES_HOST/$_slug/_data"

say "docker"
if ! docker info >/dev/null 2>&1; then open -a Docker; for _ in $(seq 1 90); do docker info >/dev/null 2>&1 && break; sleep 2; done; fi
docker info >/dev/null 2>&1 || { echo "Docker is not running" >&2; exit 1; }
say "data services (compose project hblpub)"
# The sites gateway trusts X-Forwarded-For only from the peer it measures: the Docker bridge gateway of the hblpub network (Docker Desktop NAT, cloudflared on the host
# reaches it from that address). Taken from the live network, never hard-coded; unset/unknown = 127.0.0.1 = trust nothing.
if [ -z "${GATEWAY_REAL_IP_FROM:-}" ]; then
  _gw="$(docker network inspect hblpub_default -f '{{range .IPAM.Config}}{{.Gateway}} {{end}}' 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1 || true)"
  [ -n "$_gw" ] && export GATEWAY_REAL_IP_FROM="$_gw/32"
fi
if [ -z "${API_UPSTREAM_HOST:-}" ]; then
  _h4="$(docker run --rm --entrypoint sh --add-host h:host-gateway nginxinc/nginx-unprivileged:1.29-alpine -c 'getent ahostsv4 h | head -1' 2>/dev/null | awk '{print $1}' || true)"
  [[ "$_h4" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && export API_UPSTREAM_HOST="$_h4"
fi
export GATEWAY_FORCE_HTTPS="${GATEWAY_FORCE_HTTPS:-1}"   # global mode: plain http at the edge is redirected to https at the gateway
docker compose -f compose.public.yml --env-file "$ENVF" up -d --wait

alive() { curl -fsS -m3 "$1" >/dev/null 2>&1; }
if ! alive "http://127.0.0.1:$RENDER_PORT_PUBLIC/health"; then
  say "starting the render worker (127.0.0.1:$RENDER_PORT_PUBLIC, token-protected)"
  npx tsc -p workers/render/tsconfig.json
  ( nohup env RENDER_PORT="$RENDER_PORT_PUBLIC" RENDER_TOKEN="$RENDER_TOKEN" node workers/render/dist/workers/render/server.js > "$RUN/render.log" 2>&1 < /dev/null & echo $! > "$RUN/render.pid" )
  for _ in $(seq 1 20); do alive "http://127.0.0.1:$RENDER_PORT_PUBLIC/health" && break; sleep 0.5; done
fi
if ! alive "http://127.0.0.1:$API_PORT/actuator/health/liveness"; then
  say "building the API jar"
  (cd backend && ./gradlew bootJar -x test --console=plain -q)
  JAR="$(ls -t backend/build/libs/*.jar | grep -v plain | head -1)"
  say "starting the API (profile prod) from $JAR"
  ( cd "$RUN"; nohup env SPRING_PROFILES_ACTIVE=prod APP_PROFILE=prod \
      SERVER_ADDRESS=127.0.0.1 SERVER_PORT="$API_PORT" \
      DATABASE_URL="jdbc:postgresql://127.0.0.1:$PG_PORT/studio"   \
      REDIS_HOST=127.0.0.1 REDIS_PORT="$REDIS_PORT_PUBLIC"  \
      RABBITMQ_HOST=127.0.0.1 RABBITMQ_PORT="$RABBITMQ_PORT_PUBLIC" RABBITMQ_USER=studio  \
      MINIO_ENDPOINT="http://127.0.0.1:$MINIO_PORT_PUBLIC" MINIO_PUBLIC_ENDPOINT="https://$PUBLIC_FILES_HOST"    \
      DEPLOY_PROVIDER=static SITES_ORIGIN="https://$SITES_HOST" STUDIO_ORIGIN="$PUBLIC_ORIGIN" SITES_COOKIE_SECURE=true \
      RENDER_URL="http://127.0.0.1:$RENDER_PORT_PUBLIC" RENDER_TOKEN="$RENDER_TOKEN" \
      CORS_ALLOWED_ORIGINS="$PUBLIC_ORIGIN" TRUST_PROXY=true TRUSTED_PROXY_CIDRS="${PUBLIC_TRUSTED_PROXY_CIDRS:-127.0.0.1/32,::1/128}" \
      DATA_PLATFORM_ENABLED="$V1_FEATURES" WORKFLOW_ENABLED="$V1_FEATURES" PUBLISH_CONFIGS_ENABLED="$V1_FEATURES" SITES_PUBLIC_DATA_ENABLED="$V1_FEATURES" \
      SITES_DATA_API_BASE="$SITES_DATA_API_BASE" \
      BACKUP_STATUS_DIRS="public:$ROOT/backups/public" \
      APP_DEPLOY_MOCK_BASE_URL="$PUBLIC_ORIGIN/mock-deployments" OPENROUTER_REFERER="$PUBLIC_ORIGIN" \
            \
          \
      java -XX:MaxRAMPercentage=40 -jar "$ROOT/$JAR" > api.log 2>&1 < /dev/null & echo $! > api.pid )
  for _ in $(seq 1 90); do alive "http://127.0.0.1:$API_PORT/actuator/health/readiness" && break; sleep 2; done
  alive "http://127.0.0.1:$API_PORT/actuator/health/readiness" || { echo "API did not become ready; see $RUN/api.log" >&2; tail -20 "$RUN/api.log" >&2; exit 1; }
fi

if ! alive "http://127.0.0.1:$UI_PORT/"; then
  say "building the UI (http mode)"
  export NEXT_PUBLIC_API_MODE=http NEXT_DIST_DIR=.next-public API_PROXY_TARGET="http://127.0.0.1:$API_PORT"
  if [ ! -f .next-public/BUILD_ID ] || [ -n "$(find app components features lib next.config.ts proxy.ts package.json -newer .next-public/BUILD_ID -type f 2>/dev/null | head -1)" ]; then
    npx next build > "$RUN/ui-build.log" 2>&1 || { tail -20 "$RUN/ui-build.log" >&2; exit 1; }
  fi
  say "starting the UI server"
  ( nohup env NODE_ENV=production STUDIO_HSTS=true MINIO_PUBLIC_ENDPOINT="https://$PUBLIC_FILES_HOST" SITES_ORIGIN="https://$SITES_HOST" \
      npx next start -H 127.0.0.1 -p "$UI_PORT" > "$RUN/ui.log" 2>&1 < /dev/null & echo $! > "$RUN/ui.pid" )
  for _ in $(seq 1 60); do alive "http://127.0.0.1:$UI_PORT/" && break; sleep 1; done
  alive "http://127.0.0.1:$UI_PORT/" || { echo "UI did not start; see $RUN/ui.log" >&2; exit 1; }
fi

say "Cloudflare tunnel (dedicated tunnel 'hbl-studio'; the shared 'gemma' tunnel and its config are not touched)"
command -v cloudflared >/dev/null || { echo "cloudflared is not installed" >&2; exit 1; }
TUNNEL_ID="$(cloudflared tunnel list --output json 2>/dev/null | python3 -c 'import sys,json
try:
    t=[x for x in json.load(sys.stdin) if x["name"]=="hbl-studio"]; print(t[0]["id"] if t else "")
except Exception: print("")')"
if [ -z "$TUNNEL_ID" ]; then
  cloudflared tunnel create hbl-studio > "$RUN/tunnel-create.log" 2>&1 || { cat "$RUN/tunnel-create.log" >&2; exit 1; }
  TUNNEL_ID="$(grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' "$RUN/tunnel-create.log" | head -1)"
fi
CFG="$HOME/.cloudflared/hbl-studio.yml"
# The tunnel config is written first and passed with --config, and the tunnel is addressed by UUID: otherwise cloudflared falls back
# to ~/.cloudflared/config.yml (the shared "gemma" tunnel) and would point our hostnames at the wrong tunnel.
cat > "$CFG" <<YML
tunnel: $TUNNEL_ID
credentials-file: $HOME/.cloudflared/$TUNNEL_ID.json
ingress:
  - hostname: $PUBLIC_HOST
    service: http://127.0.0.1:$UI_PORT
  - hostname: $PUBLIC_FILES_HOST
    service: http://127.0.0.1:$MINIO_PORT_PUBLIC
  - hostname: $SITES_HOST
    service: http://127.0.0.1:$SITES_GATEWAY_PORT
  - service: http_status:404
YML
for h in "$PUBLIC_HOST" "$PUBLIC_FILES_HOST" "$SITES_HOST"; do
  cloudflared tunnel --config "$CFG" route dns --overwrite-dns "$TUNNEL_ID" "$h" > "$RUN/route-$h.log" 2>&1 || { echo "DNS route for $h failed:" >&2; cat "$RUN/route-$h.log" >&2; exit 1; }
  grep -q "tunnelID=$TUNNEL_ID" "$RUN/route-$h.log" || { echo "DNS for $h was not attached to tunnel $TUNNEL_ID:" >&2; cat "$RUN/route-$h.log" >&2; exit 1; }
done
if ! { [ -f "$RUN/tunnel.pid" ] && kill -0 "$(cat "$RUN/tunnel.pid")" 2>/dev/null; }; then
  ( nohup cloudflared tunnel --config "$CFG" --no-autoupdate run "$TUNNEL_ID" > "$RUN/tunnel.log" 2>&1 < /dev/null & echo $! > "$RUN/tunnel.pid" )
fi
if [ "${KEEP_AWAKE:-true}" = true ] && ! { [ -f "$RUN/awake.pid" ] && kill -0 "$(cat "$RUN/awake.pid")" 2>/dev/null; }; then
  ( nohup caffeinate -i -s > /dev/null 2>&1 < /dev/null & echo $! > "$RUN/awake.pid" )     # no idle/AC sleep while published
fi
# scheduled backups (daily + weekly restore drill) and the process watchdog (stage L); both idempotent and detached
if [ "${BACKUP_DAEMON:-true}" = true ]; then perl -MPOSIX -e 'POSIX::setsid(); exec @ARGV' "$ROOT/scripts/backup-daemon.sh" public > /dev/null 2>&1 < /dev/null & fi
if [ "${WATCHDOG:-true}" = true ]; then perl -MPOSIX -e 'POSIX::setsid(); exec @ARGV' "$ROOT/scripts/watchdog.sh" public > /dev/null 2>&1 < /dev/null & fi
say "waiting for the public URL"
for _ in $(seq 1 60); do curl -fsS -m8 "$PUBLIC_ORIGIN/api/v1/auth/config" >/dev/null 2>&1 && break; sleep 2; done
"$ROOT/scripts/public-status.sh" || true
